// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"activity-bot/internal/emoji"
	"github.com/jackc/pgx/v5/pgtype"
)

type MarriageRequestStatus string

const (
	MarriageRequestStatusPending   MarriageRequestStatus = "pending"
	MarriageRequestStatusAccepted  MarriageRequestStatus = "accepted"
	MarriageRequestStatusRejected  MarriageRequestStatus = "rejected"
	MarriageRequestStatusCancelled MarriageRequestStatus = "cancelled"
)

func (e *MarriageRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MarriageRequestStatus(s)
	case string:
		*e = MarriageRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MarriageRequestStatus: %T", src)
	}
	return nil
}

type NullMarriageRequestStatus struct {
	MarriageRequestStatus MarriageRequestStatus `json:"marriageRequestStatus"`
	Valid                 bool                  `json:"valid"` // Valid is true if MarriageRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMarriageRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MarriageRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MarriageRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMarriageRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MarriageRequestStatus), nil
}

type ModerationType string

const (
	ModerationTypeKick ModerationType = "kick"
	ModerationTypeMute ModerationType = "mute"
	ModerationTypeBan  ModerationType = "ban"
	ModerationTypeWarn ModerationType = "warn"
)

func (e *ModerationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModerationType(s)
	case string:
		*e = ModerationType(s)
	default:
		return fmt.Errorf("unsupported scan type for ModerationType: %T", src)
	}
	return nil
}

type NullModerationType struct {
	ModerationType ModerationType `json:"moderationType"`
	Valid          bool           `json:"valid"` // Valid is true if ModerationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModerationType) Scan(value interface{}) error {
	if value == nil {
		ns.ModerationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModerationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModerationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModerationType), nil
}

type RestStatus string

const (
	RestStatusPending  RestStatus = "pending"
	RestStatusApproved RestStatus = "approved"
	RestStatusRejected RestStatus = "rejected"
)

func (e *RestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RestStatus(s)
	case string:
		*e = RestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RestStatus: %T", src)
	}
	return nil
}

type NullRestStatus struct {
	RestStatus RestStatus `json:"restStatus"`
	Valid      bool       `json:"valid"` // Valid is true if RestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RestStatus), nil
}

type BannedChat struct {
	ChatID    int64              `db:"chat_id" json:"chatId"`
	Reason    pgtype.Text        `db:"reason" json:"reason"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
}

type BannedUser struct {
	UserID    int64              `db:"user_id" json:"userId"`
	Reason    pgtype.Text        `db:"reason" json:"reason"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
}

type BotDeveloper struct {
	UserID int64  `db:"user_id" json:"userId"`
	Role   string `db:"role" json:"role"`
	ChatID int64  `db:"chat_id" json:"chatId"`
}

type Chat struct {
	ID                          int64              `db:"id" json:"id"`
	NewbieThresholdDays         int32              `db:"newbie_threshold_days" json:"newbieThresholdDays"`
	AiSystemPrompt              pgtype.Text        `db:"ai_system_prompt" json:"aiSystemPrompt"`
	MaxLadder                   int32              `db:"max_ladder" json:"maxLadder"`
	CallOnJoin                  bool               `db:"call_on_join" json:"callOnJoin"`
	WelcomeCallMessage          pgtype.Text        `db:"welcome_call_message" json:"welcomeCallMessage"`
	WeekStartDay                int16              `db:"week_start_day" json:"weekStartDay"`
	MaxWarns                    int32              `db:"max_warns" json:"maxWarns"`
	CommandPrefix               pgtype.Text        `db:"command_prefix" json:"commandPrefix"`
	AllowPrefixless             bool               `db:"allow_prefixless" json:"allowPrefixless"`
	MentionsPerMessage          int32              `db:"mentions_per_message" json:"mentionsPerMessage"`
	MentionTypes                int32              `db:"mention_types" json:"mentionTypes"`
	Title                       string             `db:"title" json:"title"`
	TagsEnabled                 bool               `db:"tags_enabled" json:"tagsEnabled"`
	WeekStartTime               pgtype.Time        `db:"week_start_time" json:"weekStartTime"`
	BroadcastEnabled            bool               `db:"broadcast_enabled" json:"broadcastEnabled"`
	RemovedAt                   pgtype.Timestamptz `db:"removed_at" json:"removedAt"`
	EmojisEnabled               bool               `db:"emojis_enabled" json:"emojisEnabled"`
	SkipCallConfirmation        bool               `db:"skip_call_confirmation" json:"skipCallConfirmation"`
	AllowPolygamy               bool               `db:"allow_polygamy" json:"allowPolygamy"`
	UsernameChangedNotifyStatus int16              `db:"username_changed_notify_status" json:"usernameChangedNotifyStatus"`
}

type ChatMember struct {
	ChatID          int64              `db:"chat_id" json:"chatId"`
	UserID          int64              `db:"user_id" json:"userId"`
	JoinedAt        pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
	RestUntil       pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	Tag             pgtype.Text        `db:"tag" json:"tag"`
	LeftAt          pgtype.Timestamptz `db:"left_at" json:"leftAt"`
	RestReason      pgtype.Text        `db:"rest_reason" json:"restReason"`
	Emoji           pgtype.Text        `db:"emoji" json:"emoji"`
	Status          int16              `db:"status" json:"status"`
	EmojiJson       emoji.Emojis       `db:"emoji_json" json:"emojiJson"`
	ExcludeFromCall bool               `db:"exclude_from_call" json:"excludeFromCall"`
	Description     pgtype.Text        `db:"description" json:"description"`
	Birthday        pgtype.Date        `db:"birthday" json:"birthday"`
}

type ChatMemberNorm struct {
	NormID int64 `db:"norm_id" json:"normId"`
	UserID int64 `db:"user_id" json:"userId"`
}

type ChatNorm struct {
	ID     int64  `db:"id" json:"id"`
	ChatID int64  `db:"chat_id" json:"chatId"`
	Name   string `db:"name" json:"name"`
	Value  int32  `db:"value" json:"value"`
}

type ChatRpCommand struct {
	ID        int64              `db:"id" json:"id"`
	ChatID    int64              `db:"chat_id" json:"chatId"`
	Trigger   string             `db:"trigger" json:"trigger"`
	Action    string             `db:"action" json:"action"`
	Emojis    string             `db:"emojis" json:"emojis"`
	CreatedBy int64              `db:"created_by" json:"createdBy"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type CommandPermission struct {
	ChatID         int64  `db:"chat_id" json:"chatId"`
	CommandKey     string `db:"command_key" json:"commandKey"`
	RequiredStatus int16  `db:"required_status" json:"requiredStatus"`
}

type CrocodileWord struct {
	ID         int64            `db:"id" json:"id"`
	Word       string           `db:"word" json:"word"`
	Category   string           `db:"category" json:"category"`
	Difficulty int16            `db:"difficulty" json:"difficulty"`
	UsedCount  int32            `db:"used_count" json:"usedCount"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"createdAt"`
	LastUsedAt pgtype.Timestamp `db:"last_used_at" json:"lastUsedAt"`
}

type Fandom struct {
	ID     int64  `db:"id" json:"id"`
	ChatID int64  `db:"chat_id" json:"chatId"`
	Name   string `db:"name" json:"name"`
}

type Marriage struct {
	ID         int64              `db:"id" json:"id"`
	ChatID     int64              `db:"chat_id" json:"chatId"`
	User1ID    int64              `db:"user1_id" json:"user1Id"`
	User2ID    int64              `db:"user2_id" json:"user2Id"`
	MarriedAt  pgtype.Timestamptz `db:"married_at" json:"marriedAt"`
	DivorcedAt pgtype.Timestamptz `db:"divorced_at" json:"divorcedAt"`
}

type MarriageRequest struct {
	ID          int64                 `db:"id" json:"id"`
	ChatID      int64                 `db:"chat_id" json:"chatId"`
	FromUserID  int64                 `db:"from_user_id" json:"fromUserId"`
	ToUserID    int64                 `db:"to_user_id" json:"toUserId"`
	Status      MarriageRequestStatus `db:"status" json:"status"`
	CreatedAt   pgtype.Timestamptz    `db:"created_at" json:"createdAt"`
	RespondedAt pgtype.Timestamptz    `db:"responded_at" json:"respondedAt"`
}

type Message struct {
	ChatID    int64              `db:"chat_id" json:"chatId"`
	UserID    int64              `db:"user_id" json:"userId"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	ID        int64              `db:"id" json:"id"`
	MessageID pgtype.Int8        `db:"message_id" json:"messageId"`
}

type ModerationAction struct {
	ID          int64              `db:"id" json:"id"`
	Type        ModerationType     `db:"type" json:"type"`
	ChatID      int64              `db:"chat_id" json:"chatId"`
	UserID      int64              `db:"user_id" json:"userId"`
	ModeratorID int64              `db:"moderator_id" json:"moderatorId"`
	Reason      pgtype.Text        `db:"reason" json:"reason"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	RevokedAt   pgtype.Timestamptz `db:"revoked_at" json:"revokedAt"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
}

type RestRequest struct {
	ChatID      int64              `db:"chat_id" json:"chatId"`
	UserID      int64              `db:"user_id" json:"userId"`
	RequestedAt pgtype.Timestamptz `db:"requested_at" json:"requestedAt"`
	RestUntil   pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	Status      RestStatus         `db:"status" json:"status"`
	MessageID   pgtype.Int8        `db:"message_id" json:"messageId"`
	Reason      pgtype.Text        `db:"reason" json:"reason"`
	ID          pgtype.Int8        `db:"id" json:"id"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type Reward struct {
	ID        int64              `db:"id" json:"id"`
	ChatID    int64              `db:"chat_id" json:"chatId"`
	UserID    int64              `db:"user_id" json:"userId"`
	AuthorID  int64              `db:"author_id" json:"authorId"`
	Rank      int16              `db:"rank" json:"rank"`
	Reason    string             `db:"reason" json:"reason"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type Role struct {
	ID         int64              `db:"id" json:"id"`
	CategoryID int64              `db:"category_id" json:"categoryId"`
	Name       string             `db:"name" json:"name"`
	Emoji      pgtype.Text        `db:"emoji" json:"emoji"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type RoleAlias struct {
	ID     int64  `db:"id" json:"id"`
	RoleID int64  `db:"role_id" json:"roleId"`
	Name   string `db:"name" json:"name"`
}

type RoleCategory struct {
	ID        int64              `db:"id" json:"id"`
	FandomID  int64              `db:"fandom_id" json:"fandomId"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	Position  int32              `db:"position" json:"position"`
}

type RoleReservation struct {
	ID        int64              `db:"id" json:"id"`
	ChatID    int64              `db:"chat_id" json:"chatId"`
	RoleID    int64              `db:"role_id" json:"roleId"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UserID    int64              `db:"user_id" json:"userId"`
}

type User struct {
	ID            int64              `db:"id" json:"id"`
	Username      pgtype.Text        `db:"username" json:"username"`
	FirstName     pgtype.Text        `db:"first_name" json:"firstName"`
	LastName      pgtype.Text        `db:"last_name" json:"lastName"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	Gender        string             `db:"gender" json:"gender"`
	Emoji         pgtype.Text        `db:"emoji" json:"emoji"`
	CustomEmojiID pgtype.Text        `db:"custom_emoji_id" json:"customEmojiId"`
	EmojiJson     emoji.Emojis       `db:"emoji_json" json:"emojiJson"`
	IsBot         bool               `db:"is_bot" json:"isBot"`
	Birthday      pgtype.Date        `db:"birthday" json:"birthday"`
}

type UserPmSession struct {
	UserID       int64              `db:"user_id" json:"userId"`
	TargetChatID int64              `db:"target_chat_id" json:"targetChatId"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}
