// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (category_id,
                   name,
                   emoji)
VALUES ($1, $2, $3)
ON CONFLICT (category_id, name)
    DO UPDATE SET emoji = EXCLUDED.emoji
RETURNING
    id,
    category_id,
    name,
    emoji,
    created_at
`

type CreateRoleParams struct {
	CategoryID int64       `db:"category_id" json:"categoryId"`
	Name       string      `db:"name" json:"name"`
	Emoji      pgtype.Text `db:"emoji" json:"emoji"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.CategoryID, arg.Name, arg.Emoji)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Emoji,
		&i.CreatedAt,
	)
	return i, err
}

const createRoleAlias = `-- name: CreateRoleAlias :one
INSERT INTO role_aliases (role_id,
                          name)
VALUES ($1, $2)
ON CONFLICT (role_id, name)
    DO NOTHING
RETURNING
    id,
    role_id,
    name
`

type CreateRoleAliasParams struct {
	RoleID int64  `db:"role_id" json:"roleId"`
	Name   string `db:"name" json:"name"`
}

func (q *Queries) CreateRoleAlias(ctx context.Context, arg CreateRoleAliasParams) (RoleAlias, error) {
	row := q.db.QueryRow(ctx, createRoleAlias, arg.RoleID, arg.Name)
	var i RoleAlias
	err := row.Scan(&i.ID, &i.RoleID, &i.Name)
	return i, err
}

const createRoleCategory = `-- name: CreateRoleCategory :one
INSERT INTO role_categories (fandom_id,
                             name)
VALUES ($1, $2)
ON CONFLICT (fandom_id, name)
    DO UPDATE SET name = EXCLUDED.name
RETURNING
    id,
    fandom_id,
    name,
    created_at
`

type CreateRoleCategoryParams struct {
	FandomID int64  `db:"fandom_id" json:"fandomId"`
	Name     string `db:"name" json:"name"`
}

func (q *Queries) CreateRoleCategory(ctx context.Context, arg CreateRoleCategoryParams) (RoleCategory, error) {
	row := q.db.QueryRow(ctx, createRoleCategory, arg.FandomID, arg.Name)
	var i RoleCategory
	err := row.Scan(
		&i.ID,
		&i.FandomID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createRoleReservation = `-- name: CreateRoleReservation :exec
INSERT INTO role_reservations (chat_id,
                               user_id,
                               role_id)
VALUES ($1, $2, $3)
ON CONFLICT (chat_id, role_id)
    DO NOTHING
`

type CreateRoleReservationParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
	RoleID int64 `db:"role_id" json:"roleId"`
}

func (q *Queries) CreateRoleReservation(ctx context.Context, arg CreateRoleReservationParams) error {
	_, err := q.db.Exec(ctx, createRoleReservation, arg.ChatID, arg.UserID, arg.RoleID)
	return err
}

const deleteFandom = `-- name: DeleteFandom :exec
DELETE FROM fandoms WHERE chat_id = $1 AND name = $2
`

type DeleteFandomParams struct {
	ChatID int64  `db:"chat_id" json:"chatId"`
	Name   string `db:"name" json:"name"`
}

func (q *Queries) DeleteFandom(ctx context.Context, arg DeleteFandomParams) error {
	_, err := q.db.Exec(ctx, deleteFandom, arg.ChatID, arg.Name)
	return err
}

const deleteRoleReservation = `-- name: DeleteRoleReservation :exec
DELETE
FROM role_reservations
WHERE chat_id = $1
  AND role_id = $2
`

type DeleteRoleReservationParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	RoleID int64 `db:"role_id" json:"roleId"`
}

func (q *Queries) DeleteRoleReservation(ctx context.Context, arg DeleteRoleReservationParams) error {
	_, err := q.db.Exec(ctx, deleteRoleReservation, arg.ChatID, arg.RoleID)
	return err
}

const getFandom = `-- name: GetFandom :one
SELECT id, chat_id, name
FROM fandoms
WHERE chat_id = $1
  AND name = $2
`

type GetFandomParams struct {
	ChatID int64  `db:"chat_id" json:"chatId"`
	Name   string `db:"name" json:"name"`
}

func (q *Queries) GetFandom(ctx context.Context, arg GetFandomParams) (Fandom, error) {
	row := q.db.QueryRow(ctx, getFandom, arg.ChatID, arg.Name)
	var i Fandom
	err := row.Scan(&i.ID, &i.ChatID, &i.Name)
	return i, err
}

const getFandomWithRoles = `-- name: GetFandomWithRoles :many
SELECT f.id          AS fandom_id,
       f.chat_id     AS fandom_chat_id,
       f.name        AS fandom_name,

       rc.id         AS category_id,
       rc.fandom_id  AS category_fandom_id,
       rc.name       AS category_name,
       rc.created_at AS category_created_at,

       r.id          AS role_id,
       r.category_id AS role_category_id,
       r.name        AS role_name,
       r.emoji       AS role_emoji,
       r.created_at  AS role_created_at,

       ra.id         AS alias_id,
       ra.role_id    AS alias_role_id,
       ra.name       AS alias_name
FROM fandoms f
         LEFT JOIN role_categories rc
                   ON rc.fandom_id = f.id
         LEFT JOIN roles r
                   ON r.category_id = rc.id
         LEFT JOIN role_aliases ra
                   ON ra.role_id = r.id
WHERE f.chat_id = $1
  AND f.name = $2
ORDER BY rc.created_at,
         r.name,
         ra.name
`

type GetFandomWithRolesParams struct {
	ChatID int64  `db:"chat_id" json:"chatId"`
	Name   string `db:"name" json:"name"`
}

type GetFandomWithRolesRow struct {
	FandomID          int64              `db:"fandom_id" json:"fandomId"`
	FandomChatID      int64              `db:"fandom_chat_id" json:"fandomChatId"`
	FandomName        string             `db:"fandom_name" json:"fandomName"`
	CategoryID        pgtype.Int8        `db:"category_id" json:"categoryId"`
	CategoryFandomID  pgtype.Int8        `db:"category_fandom_id" json:"categoryFandomId"`
	CategoryName      pgtype.Text        `db:"category_name" json:"categoryName"`
	CategoryCreatedAt pgtype.Timestamptz `db:"category_created_at" json:"categoryCreatedAt"`
	RoleID            pgtype.Int8        `db:"role_id" json:"roleId"`
	RoleCategoryID    pgtype.Int8        `db:"role_category_id" json:"roleCategoryId"`
	RoleName          pgtype.Text        `db:"role_name" json:"roleName"`
	RoleEmoji         pgtype.Text        `db:"role_emoji" json:"roleEmoji"`
	RoleCreatedAt     pgtype.Timestamptz `db:"role_created_at" json:"roleCreatedAt"`
	AliasID           pgtype.Int8        `db:"alias_id" json:"aliasId"`
	AliasRoleID       pgtype.Int8        `db:"alias_role_id" json:"aliasRoleId"`
	AliasName         pgtype.Text        `db:"alias_name" json:"aliasName"`
}

func (q *Queries) GetFandomWithRoles(ctx context.Context, arg GetFandomWithRolesParams) ([]GetFandomWithRolesRow, error) {
	rows, err := q.db.Query(ctx, getFandomWithRoles, arg.ChatID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFandomWithRolesRow{}
	for rows.Next() {
		var i GetFandomWithRolesRow
		if err := rows.Scan(
			&i.FandomID,
			&i.FandomChatID,
			&i.FandomName,
			&i.CategoryID,
			&i.CategoryFandomID,
			&i.CategoryName,
			&i.CategoryCreatedAt,
			&i.RoleID,
			&i.RoleCategoryID,
			&i.RoleName,
			&i.RoleEmoji,
			&i.RoleCreatedAt,
			&i.AliasID,
			&i.AliasRoleID,
			&i.AliasName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateFandom = `-- name: GetOrCreateFandom :one
INSERT INTO fandoms (chat_id,
                     name)
VALUES ($1, $2)
ON CONFLICT (chat_id, name)
    DO UPDATE SET name = EXCLUDED.name
RETURNING
    id,
    chat_id,
    name
`

type GetOrCreateFandomParams struct {
	ChatID int64  `db:"chat_id" json:"chatId"`
	Name   string `db:"name" json:"name"`
}

func (q *Queries) GetOrCreateFandom(ctx context.Context, arg GetOrCreateFandomParams) (Fandom, error) {
	row := q.db.QueryRow(ctx, getOrCreateFandom, arg.ChatID, arg.Name)
	var i Fandom
	err := row.Scan(&i.ID, &i.ChatID, &i.Name)
	return i, err
}

const getRoleByAlias = `-- name: GetRoleByAlias :one
SELECT r.id, r.category_id, r.name, r.emoji, r.created_at
FROM roles r
         JOIN role_aliases ra ON ra.role_id = r.id
         JOIN role_categories rc ON rc.id = r.category_id
         JOIN fandoms f ON f.id = rc.fandom_id
WHERE f.chat_id = $1
  AND f.name = $2
  AND ra.name = $3
`

type GetRoleByAliasParams struct {
	ChatID int64  `db:"chat_id" json:"chatId"`
	Name   string `db:"name" json:"name"`
	Name_2 string `db:"name_2" json:"name2"`
}

func (q *Queries) GetRoleByAlias(ctx context.Context, arg GetRoleByAliasParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByAlias, arg.ChatID, arg.Name, arg.Name_2)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Emoji,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT r.id, r.category_id, r.name, r.emoji, r.created_at
FROM roles r
         JOIN role_categories rc ON rc.id = r.category_id
         JOIN fandoms f ON f.id = rc.fandom_id
WHERE f.chat_id = $1
  AND f.name = $2
  AND rc.name = $3
  AND r.name = $4
`

type GetRoleByNameParams struct {
	ChatID int64  `db:"chat_id" json:"chatId"`
	Name   string `db:"name" json:"name"`
	Name_2 string `db:"name_2" json:"name2"`
	Name_3 string `db:"name_3" json:"name3"`
}

func (q *Queries) GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName,
		arg.ChatID,
		arg.Name,
		arg.Name_2,
		arg.Name_3,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Emoji,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByNameOrAlias = `-- name: GetRoleByNameOrAlias :one
SELECT r.id, r.category_id, r.name, r.emoji, r.created_at
FROM roles r
         JOIN role_categories rc ON rc.id = r.category_id
         JOIN fandoms f ON f.id = rc.fandom_id
         LEFT JOIN role_aliases ra ON ra.role_id = r.id
WHERE f.chat_id = $1
  AND LOWER(f.name) = LOWER($2)
  AND (
    LOWER(r.name) = LOWER($3)
        OR LOWER(ra.name) = LOWER($3)
    )
LIMIT 1
`

type GetRoleByNameOrAliasParams struct {
	ChatID  int64  `db:"chat_id" json:"chatId"`
	Lower   string `db:"lower" json:"lower"`
	Lower_2 string `db:"lower_2" json:"lower2"`
}

func (q *Queries) GetRoleByNameOrAlias(ctx context.Context, arg GetRoleByNameOrAliasParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByNameOrAlias, arg.ChatID, arg.Lower, arg.Lower_2)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Emoji,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleCategory = `-- name: GetRoleCategory :one
SELECT id,
       fandom_id,
       name,
       created_at
FROM role_categories
WHERE fandom_id = $1
  AND name = $2
`

type GetRoleCategoryParams struct {
	FandomID int64  `db:"fandom_id" json:"fandomId"`
	Name     string `db:"name" json:"name"`
}

func (q *Queries) GetRoleCategory(ctx context.Context, arg GetRoleCategoryParams) (RoleCategory, error) {
	row := q.db.QueryRow(ctx, getRoleCategory, arg.FandomID, arg.Name)
	var i RoleCategory
	err := row.Scan(
		&i.ID,
		&i.FandomID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleReservation = `-- name: GetRoleReservation :one
SELECT id, chat_id, role_id, created_at, user_id
FROM role_reservations
WHERE chat_id = $1
  AND role_id = $2
`

type GetRoleReservationParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	RoleID int64 `db:"role_id" json:"roleId"`
}

func (q *Queries) GetRoleReservation(ctx context.Context, arg GetRoleReservationParams) (RoleReservation, error) {
	row := q.db.QueryRow(ctx, getRoleReservation, arg.ChatID, arg.RoleID)
	var i RoleReservation
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const listRoleCategories = `-- name: ListRoleCategories :many
SELECT id,
       fandom_id,
       name,
       created_at
FROM role_categories
WHERE fandom_id = $1
ORDER BY name
`

func (q *Queries) ListRoleCategories(ctx context.Context, fandomID int64) ([]RoleCategory, error) {
	rows, err := q.db.Query(ctx, listRoleCategories, fandomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleCategory{}
	for rows.Next() {
		var i RoleCategory
		if err := rows.Scan(
			&i.ID,
			&i.FandomID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleReservations = `-- name: ListRoleReservations :many
SELECT rr.id, rr.chat_id, rr.role_id, rr.created_at, rr.user_id,
       r.id, r.category_id, r.name, r.emoji, r.created_at,
       rc.id, rc.fandom_id, rc.name, rc.created_at,
       f.id, f.chat_id, f.name
FROM role_reservations rr
         JOIN roles r ON r.id = rr.role_id
         JOIN role_categories rc ON rc.id = r.category_id
         JOIN fandoms f ON f.id = rc.fandom_id
WHERE rr.chat_id = $1
ORDER BY f.name, rc.name, r.name
`

type ListRoleReservationsRow struct {
	RoleReservation RoleReservation `db:"role_reservation" json:"roleReservation"`
	Role            Role            `db:"role" json:"role"`
	RoleCategory    RoleCategory    `db:"role_category" json:"roleCategory"`
	Fandom          Fandom          `db:"fandom" json:"fandom"`
}

func (q *Queries) ListRoleReservations(ctx context.Context, chatID int64) ([]ListRoleReservationsRow, error) {
	rows, err := q.db.Query(ctx, listRoleReservations, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoleReservationsRow{}
	for rows.Next() {
		var i ListRoleReservationsRow
		if err := rows.Scan(
			&i.RoleReservation.ID,
			&i.RoleReservation.ChatID,
			&i.RoleReservation.RoleID,
			&i.RoleReservation.CreatedAt,
			&i.RoleReservation.UserID,
			&i.Role.ID,
			&i.Role.CategoryID,
			&i.Role.Name,
			&i.Role.Emoji,
			&i.Role.CreatedAt,
			&i.RoleCategory.ID,
			&i.RoleCategory.FandomID,
			&i.RoleCategory.Name,
			&i.RoleCategory.CreatedAt,
			&i.Fandom.ID,
			&i.Fandom.ChatID,
			&i.Fandom.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleTemplates = `-- name: ListRoleTemplates :many
SELECT f.id          AS fandom_id,
       f.chat_id     AS fandom_chat_id,
       f.name        AS fandom_name,

       rc.id         AS category_id,
       rc.fandom_id  AS category_fandom_id,
       rc.name       AS category_name,
       rc.created_at AS category_created_at,

       r.id          AS role_id,
       r.category_id AS role_category_id,
       r.name        AS role_name,
       r.emoji       AS role_emoji,
       r.created_at  AS role_created_at,

       ra.id         AS alias_id,
       ra.role_id    AS alias_role_id,
       ra.name       AS alias_name
FROM fandoms f
         JOIN role_categories rc
              ON rc.fandom_id = f.id
         JOIN roles r
              ON r.category_id = rc.id
         LEFT JOIN role_aliases ra
                   ON ra.role_id = r.id
WHERE f.chat_id = $1
ORDER BY f.name,
         rc.id,
         r.name,
         ra.name
`

type ListRoleTemplatesRow struct {
	FandomID          int64              `db:"fandom_id" json:"fandomId"`
	FandomChatID      int64              `db:"fandom_chat_id" json:"fandomChatId"`
	FandomName        string             `db:"fandom_name" json:"fandomName"`
	CategoryID        int64              `db:"category_id" json:"categoryId"`
	CategoryFandomID  int64              `db:"category_fandom_id" json:"categoryFandomId"`
	CategoryName      string             `db:"category_name" json:"categoryName"`
	CategoryCreatedAt pgtype.Timestamptz `db:"category_created_at" json:"categoryCreatedAt"`
	RoleID            int64              `db:"role_id" json:"roleId"`
	RoleCategoryID    int64              `db:"role_category_id" json:"roleCategoryId"`
	RoleName          string             `db:"role_name" json:"roleName"`
	RoleEmoji         pgtype.Text        `db:"role_emoji" json:"roleEmoji"`
	RoleCreatedAt     pgtype.Timestamptz `db:"role_created_at" json:"roleCreatedAt"`
	AliasID           pgtype.Int8        `db:"alias_id" json:"aliasId"`
	AliasRoleID       pgtype.Int8        `db:"alias_role_id" json:"aliasRoleId"`
	AliasName         pgtype.Text        `db:"alias_name" json:"aliasName"`
}

func (q *Queries) ListRoleTemplates(ctx context.Context, chatID int64) ([]ListRoleTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listRoleTemplates, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoleTemplatesRow{}
	for rows.Next() {
		var i ListRoleTemplatesRow
		if err := rows.Scan(
			&i.FandomID,
			&i.FandomChatID,
			&i.FandomName,
			&i.CategoryID,
			&i.CategoryFandomID,
			&i.CategoryName,
			&i.CategoryCreatedAt,
			&i.RoleID,
			&i.RoleCategoryID,
			&i.RoleName,
			&i.RoleEmoji,
			&i.RoleCreatedAt,
			&i.AliasID,
			&i.AliasRoleID,
			&i.AliasName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
