// Code generated by go generate; DO NOT EDIT.

package i18n

type MessageID string

var (
	ArgType = struct {
		Datetime MessageID
		Duration MessageID
		Number   MessageID
		Text     MessageID
		User     MessageID
	}{
		Datetime: "arg_type.datetime",
		Duration: "arg_type.duration",
		Number:   "arg_type.number",
		Text:     "arg_type.text",
		User:     "arg_type.user",
	}
	Category = struct {
		Chat       MessageID
		ChatMember MessageID
		Crocodile  MessageID
		Fun        MessageID
		Help       MessageID
		Marriage   MessageID
		Moderation MessageID
		Norm       MessageID
		Permission MessageID
		Rest       MessageID
		Rewards    MessageID
		Rp         MessageID
		Stats      MessageID
		Summon     MessageID
		User       MessageID
	}{
		Chat:       "category.chat",
		ChatMember: "category.chat_member",
		Crocodile:  "category.crocodile",
		Fun:        "category.fun",
		Help:       "category.help",
		Marriage:   "category.marriage",
		Moderation: "category.moderation",
		Norm:       "category.norm",
		Permission: "category.permission",
		Rest:       "category.rest",
		Rewards:    "category.rewards",
		Rp:         "category.rp",
		Stats:      "category.stats",
		Summon:     "category.summon",
		User:       "category.user",
	}
	Cmd = struct {
		AddNorm struct {
			Added           MessageID
			Desc            MessageID
			ErrInvalidValue MessageID
			ExampleNamed    MessageID
			ExampleSimple   MessageID
			ExampleUsers    MessageID
			NormGeneral     MessageID
		}
		AddRp struct {
			Desc     MessageID
			Example1 MessageID
			Example2 MessageID
			Success  MessageID
		}
		AdminDivorce struct {
			Desc          MessageID
			Error         MessageID
			InvalidTarget MessageID
			NoMarriage    MessageID
			Success       MessageID
		}
		AdminMarry struct {
			AlreadyMarried MessageID
			Desc           MessageID
			Error          MessageID
			InvalidTarget  MessageID
			Success        MessageID
		}
		Ai struct {
			Desc MessageID
		}
		AllRests struct {
			Desc  MessageID
			Empty MessageID
			Item  MessageID
			Title MessageID
		}
		AssignNorm struct {
			Assigned MessageID
			Desc     MessageID
			Example  MessageID
			NoUsers  MessageID
		}
		Chat struct {
			DisableEmojis struct {
				Desc    MessageID
				Success MessageID
			}
			DisablePrefixless struct {
				Desc    MessageID
				Success MessageID
			}
			EnableEmojis struct {
				Desc    MessageID
				Success MessageID
			}
			EnablePrefixless struct {
				Desc    MessageID
				Success MessageID
			}
			SetNewbieThreshold struct {
				Desc  MessageID
				Error struct {
					InvalidNumber MessageID
				}
				Success MessageID
			}
			SetNotifyUsernameChangedStatus struct {
				Desc    MessageID
				Success MessageID
			}
			SetPrefix struct {
				Desc  MessageID
				Error struct {
					Empty MessageID
				}
				Success struct {
					Custom  MessageID
					Default MessageID
				}
			}
			SetPrompt struct {
				Desc    MessageID
				Success MessageID
			}
			SetWeekStart struct {
				Desc    MessageID
				Success MessageID
			}
			ShowEmojis struct {
				Desc     MessageID
				Disabled MessageID
				Enabled  MessageID
			}
			ShowNewbieThreshold struct {
				Desc    MessageID
				Success MessageID
			}
			ShowPrefix struct {
				Desc    MessageID
				Success struct {
					Custom  MessageID
					Default MessageID
				}
			}
			ShowPrefixless struct {
				Desc     MessageID
				Disabled MessageID
				Enabled  MessageID
			}
			ShowPrompt struct {
				Desc    MessageID
				Success MessageID
			}
			ShowWeekStart struct {
				Desc    MessageID
				Success MessageID
			}
		}
		ChatMember struct {
			Birthday struct {
				Set struct {
					Desc    MessageID
					Success MessageID
				}
			}
			DeleteDescription struct {
				Desc    MessageID
				Success MessageID
			}
			RemoveEmoji struct {
				Desc    MessageID
				Success MessageID
			}
			SetDescription struct {
				Desc    MessageID
				Success MessageID
				TooLong MessageID
			}
			SetEmoji struct {
				Desc    MessageID
				Success MessageID
			}
			ShowEmoji struct {
				Desc    MessageID
				NoEmoji MessageID
				Success MessageID
			}
			Update struct {
				Desc    MessageID
				Success MessageID
			}
		}
		Crocodile struct {
			AlreadyStarted MessageID
			Button         struct {
				BecomeHost MessageID
				Finish     MessageID
				Next       MessageID
				ShowWord   MessageID
			}
			Callback struct {
				Finished MessageID
				Host     MessageID
				Next     MessageID
				Word     MessageID
			}
			Continued MessageID
			Desc      MessageID
			Error     struct {
				AlreadyStarted MessageID
				Finish         MessageID
				NextWord       MessageID
				NotHost        MessageID
				NotStarted     MessageID
				Start          MessageID
			}
			Game struct {
				Ended MessageID
			}
			Host struct {
				Left MessageID
			}
			Skip struct {
				Success MessageID
			}
			Started             MessageID
			StartedSkippedWords MessageID
			Stop                struct {
				Desc MessageID
			}
			Stopped MessageID
			Timeout struct {
				Message MessageID
			}
			Winner MessageID
			Word   MessageID
		}
		DelRp struct {
			Desc    MessageID
			Success MessageID
		}
		DeleteNorm struct {
			Deleted            MessageID
			Desc               MessageID
			ErrNothingToDelete MessageID
			Example            MessageID
		}
		DisablePolygamy struct {
			Desc    MessageID
			Success MessageID
		}
		Divorce struct {
			Announce         MessageID
			AnnouncePolygamy MessageID
			Desc             MessageID
			Error            struct {
				Divorce         MessageID
				NoMarriage      MessageID
				NotYourMarriage MessageID
			}
			Self MessageID
		}
		EnablePolygamy struct {
			Desc    MessageID
			Success MessageID
		}
		EndRest struct {
			Desc          MessageID
			Ended         MessageID
			EndedSelf     MessageID
			NotInRest     MessageID
			NotInRestSelf MessageID
		}
		FakeLeave struct {
			Desc MessageID
		}
		Help struct {
			Access         MessageID
			AliasesLabel   MessageID
			Body           MessageID
			ButtonBack     MessageID
			ButtonCommands MessageID
			ChooseCategory MessageID
			Desc           MessageID
			DisableInfo    MessageID
			EnableInfo     MessageID
			Examples       MessageID
			Page           MessageID
			Syntax         MessageID
		}
		HelpCommand struct {
			Desc MessageID
		}
		Inactive struct {
			Desc            MessageID
			EmptyList       MessageID
			Never           MessageID
			NoUsersToSummon MessageID
			SummonButton    MessageID
			Title           MessageID
			User            MessageID
		}
		ListNorms struct {
			Desc  MessageID
			Empty MessageID
			Item  MessageID
			Title MessageID
		}
		ListRewards struct {
			Desc      MessageID
			Given     MessageID
			NoRewards MessageID
			Title     MessageID
		}
		ListRp struct {
			Desc  MessageID
			Empty MessageID
			Title MessageID
		}
		Manage struct {
			Desc     MessageID
			NoChats  MessageID
			NotFound MessageID
			Select   MessageID
			Selected MessageID
			Success  MessageID
			Untitled MessageID
		}
		Marriage struct {
			Active     MessageID
			ActiveMany MessageID
			Desc       MessageID
			Error      struct {
				Load   MessageID
				Reject MessageID
			}
			None MessageID
			Self MessageID
		}
		Marriages struct {
			Category struct {
				Calico    MessageID
				CastIron  MessageID
				Copper    MessageID
				Faience   MessageID
				Green     MessageID
				Leather   MessageID
				Linen     MessageID
				Newlyweds MessageID
				Paper     MessageID
				Rose      MessageID
				Tin       MessageID
				Unknown   MessageID
				Wooden    MessageID
				Years     MessageID
			}
			Desc  MessageID
			Error struct {
				Load MessageID
			}
			None     MessageID
			Together MessageID
		}
		Marry struct {
			Accepted             MessageID
			Announce1            MessageID
			Announce2            MessageID
			Announce3            MessageID
			Announce4            MessageID
			Announce5            MessageID
			Announce6            MessageID
			AnnouncePolygamy1    MessageID
			AnnouncePolygamy2    MessageID
			AnnouncePolygamy3    MessageID
			AnnouncePolygamy4    MessageID
			AnnouncePolygamy5    MessageID
			AnnouncePolygamy6    MessageID
			AutoAccepted         MessageID
			AutoAcceptedPolygamy MessageID
			Bot                  MessageID
			BotSelf              MessageID
			Button               struct {
				Accept MessageID
				Reject MessageID
			}
			Callback struct {
				Accepted MessageID
				Rejected MessageID
			}
			Desc           MessageID
			Direct         MessageID
			DirectPolygamy MessageID
			Error          struct {
				Accept         MessageID
				AlreadyMarried MessageID
				InvalidTarget  MessageID
				Reject         MessageID
				RequestExists  MessageID
			}
			Rejected        MessageID
			Request         MessageID
			RequestPolygamy MessageID
			Self            MessageID
		}
		Moderation struct {
			Actions struct {
				Ban  MessageID
				Kick MessageID
				Mute MessageID
				Warn MessageID
			}
			Ban struct {
				Desc MessageID
			}
			Chatoff struct {
				Desc MessageID
			}
			Chaton struct {
				Desc MessageID
			}
			ClearWarns struct {
				Desc    MessageID
				Success MessageID
			}
			DeleteMessage struct {
				Desc MessageID
			}
			Demote struct {
				Desc MessageID
			}
			Kick struct {
				Desc MessageID
			}
			ListAdmins struct {
				Desc   MessageID
				Empty  MessageID
				Header MessageID
			}
			ListRoles struct {
				Desc   MessageID
				Empty  MessageID
				Header MessageID
			}
			MaxWarns struct {
				Desc MessageID
				Show MessageID
			}
			Mute struct {
				Desc MessageID
			}
			Promote struct {
				Desc MessageID
			}
			RemoveAdmin struct {
				CantModerate MessageID
				Desc         MessageID
				Success      MessageID
			}
			Rights struct {
				CanChangeInfo      MessageID
				CanDeleteMessages  MessageID
				CanInviteUsers     MessageID
				CanManageChat      MessageID
				CanManageTopics    MessageID
				CanPinMessages     MessageID
				CanPromoteMembers  MessageID
				CanRestrictMembers MessageID
				UpdateFailed       MessageID
				Updated            MessageID
			}
			SetMaxWarns struct {
				Desc MessageID
				Set  MessageID
			}
			SetRole struct {
				ChatAdmin   MessageID
				ChatCreator MessageID
				Desc        MessageID
				NoRights    MessageID
				Set         MessageID
			}
			SetRoleAdmin struct {
				ChatAdmin   MessageID
				ChatCreator MessageID
				Desc        MessageID
				NoRights    MessageID
			}
			SetStatus struct {
				CantModerate  MessageID
				Desc          MessageID
				InvalidStatus MessageID
				Success       MessageID
			}
			ShowWarns struct {
				Desc    MessageID
				Empty   MessageID
				Expires MessageID
				Header  MessageID
				Item    MessageID
				Reason  MessageID
			}
			Templates struct {
				Action    MessageID
				Forever   MessageID
				Moderator MessageID
				Reason    MessageID
				Until     MessageID
				Warns     MessageID
			}
			Unban struct {
				Desc     MessageID
				Unbanned MessageID
			}
			Unwarn struct {
				Desc    MessageID
				Success MessageID
			}
			Warn struct {
				Desc MessageID
			}
			WarnList struct {
				Desc    MessageID
				Empty   MessageID
				Expires MessageID
				Header  MessageID
				Item    MessageID
				Reason  MessageID
			}
		}
		Permission struct {
			Set struct {
				CannotAllowMembers MessageID
				CannotDisable      MessageID
				Desc               MessageID
				Success            MessageID
				UnknownCommand     MessageID
			}
			Show struct {
				Desc    MessageID
				Success MessageID
			}
		}
		Profile struct {
			Activity          MessageID
			AllNormsPassed    MessageID
			Desc              MessageID
			ExampleDate       MessageID
			ExampleDuration   MessageID
			MemberPeriod      MessageID
			MemberSince       MessageID
			NewbieExempt      MessageID
			NormFailed        MessageID
			NormPassed        MessageID
			NormsStatusHeader MessageID
			RestExempt        MessageID
			RestUntil         MessageID
			Rewards           MessageID
			RewardsButton     MessageID
			Title             MessageID
			TotalMessages     MessageID
		}
		Rest struct {
			Desc       MessageID
			Info       MessageID
			InfoReason MessageID
			NoRest     MessageID
			Set        MessageID
			SetReason  MessageID
		}
		RestRequest struct {
			ApproveButton MessageID
			Approved      MessageID
			ApprovedShort MessageID
			Created       MessageID
			Empty         MessageID
			Item          MessageID
			NoRequest     MessageID
			RejectButton  MessageID
			Rejected      MessageID
			Text          MessageID
			TextReason    MessageID
			Title         MessageID
		}
		Rests struct {
			Delete struct {
				Deleted       MessageID
				DeletedActive MessageID
				Desc          MessageID
			}
			Desc              MessageID
			HistoryEmpty      MessageID
			HistoryItem       MessageID
			HistoryItemReason MessageID
			HistoryTitle      MessageID
			HistoryTotal      MessageID
		}
		Reward struct {
			Desc    MessageID
			Success MessageID
		}
		Roles struct {
			Free struct {
				Desc    MessageID
				Success MessageID
			}
			Genshin struct {
				Desc    MessageID
				Success MessageID
			}
			Reserve struct {
				Desc    MessageID
				Success MessageID
			}
		}
		Rp struct {
			ChooseGender MessageID
			GenderFemale MessageID
			GenderMale   MessageID
			Speech       MessageID
		}
		Ship struct {
			Bot1    MessageID
			Bot2    MessageID
			Bot3    MessageID
			Bot4    MessageID
			Bot5    MessageID
			Bot6    MessageID
			Bot7    MessageID
			Bot8    MessageID
			BotBot1 MessageID
			BotBot2 MessageID
			BotBot3 MessageID
			BotBot4 MessageID
			BotBot5 MessageID
			BotBot6 MessageID
			BotBot7 MessageID
			BotBot8 MessageID
			Desc    MessageID
			None    MessageID
			Normal1 MessageID
			Normal2 MessageID
			Normal3 MessageID
			Normal4 MessageID
			Normal5 MessageID
			Normal6 MessageID
			Normal7 MessageID
			Normal8 MessageID
			Self1   MessageID
			Self2   MessageID
			Self3   MessageID
			Self4   MessageID
			Self5   MessageID
			Self6   MessageID
			Self7   MessageID
			Self8   MessageID
		}
		ShowNorm struct {
			AllMembers MessageID
			Body       MessageID
			Desc       MessageID
			Example    MessageID
			Members    MessageID
			NotFound   MessageID
		}
		Stats struct {
			AllPassed        MessageID
			AskForNormName   MessageID
			AskForSummonText MessageID
			Desc             MessageID
			EmptyList        MessageID
			ExampleDate      MessageID
			ExampleDuration  MessageID
			Failed           MessageID
			Newbies          MessageID
			NobodyToSummon   MessageID
			NormNotFound     MessageID
			NormTitle        MessageID
			Passed           MessageID
			Resting          MessageID
			SummonNoNorm     MessageID
			Title            MessageID
			TotalMessages    MessageID
			UserFailed       MessageID
			UserPassed       MessageID
		}
		StopCrocodile struct {
			Desc MessageID
		}
		Summon struct {
			AlreadyRunning MessageID
			Completed      MessageID
			Confirm        struct {
				Canceled             MessageID
				Disabled             MessageID
				No                   MessageID
				OnlyInitiatorCancel  MessageID
				OnlyInitiatorConfirm MessageID
				Text                 MessageID
				Yes                  MessageID
				YesAndDisable        MessageID
			}
			Desc      MessageID
			EnterText MessageID
			Reg       struct {
				Desc MessageID
				Set  MessageID
			}
			Style struct {
				Desc   MessageID
				Emoji  MessageID
				Name   MessageID
				Role   MessageID
				Text   MessageID
				Toggle struct {
					Desc MessageID
				}
			}
			Unreg struct {
				Desc MessageID
				Set  MessageID
			}
		}
		SummonSpecific struct {
			Desc MessageID
		}
		Top struct {
			Desc MessageID
		}
		UnassignNorm struct {
			Desc       MessageID
			Example    MessageID
			NoUsers    MessageID
			Unassigned MessageID
		}
		Unreward struct {
			Desc    MessageID
			Success MessageID
		}
		User struct {
			RemoveEmoji struct {
				Desc    MessageID
				Success MessageID
			}
			SetEmoji struct {
				Desc    MessageID
				Success MessageID
			}
			SetGender struct {
				Desc    MessageID
				Success MessageID
			}
			ShowEmoji struct {
				Desc    MessageID
				NoEmoji MessageID
				Success MessageID
			}
			ShowGender struct {
				Desc    MessageID
				Success MessageID
			}
		}
		Weather struct {
			Current  MessageID
			Day      MessageID
			Desc     MessageID
			Evening  MessageID
			Failed   MessageID
			Message  MessageID
			Morning  MessageID
			Night    MessageID
			Today    MessageID
			Tomorrow MessageID
		}
		WhoIs struct {
			Desc     MessageID
			Success1 MessageID
			Success2 MessageID
			Success3 MessageID
			Success4 MessageID
			Success5 MessageID
			Success6 MessageID
			Success7 MessageID
			Success8 MessageID
		}
	}{
		AddNorm: struct {
			Added           MessageID
			Desc            MessageID
			ErrInvalidValue MessageID
			ExampleNamed    MessageID
			ExampleSimple   MessageID
			ExampleUsers    MessageID
			NormGeneral     MessageID
		}{
			Added:           "cmd.add_norm.added",
			Desc:            "cmd.add_norm.desc",
			ErrInvalidValue: "cmd.add_norm.err_invalid_value",
			ExampleNamed:    "cmd.add_norm.example_named",
			ExampleSimple:   "cmd.add_norm.example_simple",
			ExampleUsers:    "cmd.add_norm.example_users",
			NormGeneral:     "cmd.add_norm.norm_general",
		},
		AddRp: struct {
			Desc     MessageID
			Example1 MessageID
			Example2 MessageID
			Success  MessageID
		}{
			Desc:     "cmd.add_rp.desc",
			Example1: "cmd.add_rp.example_1",
			Example2: "cmd.add_rp.example_2",
			Success:  "cmd.add_rp.success",
		},
		AdminDivorce: struct {
			Desc          MessageID
			Error         MessageID
			InvalidTarget MessageID
			NoMarriage    MessageID
			Success       MessageID
		}{
			Desc:          "cmd.admin_divorce.desc",
			Error:         "cmd.admin_divorce.error",
			InvalidTarget: "cmd.admin_divorce.invalid_target",
			NoMarriage:    "cmd.admin_divorce.no_marriage",
			Success:       "cmd.admin_divorce.success",
		},
		AdminMarry: struct {
			AlreadyMarried MessageID
			Desc           MessageID
			Error          MessageID
			InvalidTarget  MessageID
			Success        MessageID
		}{
			AlreadyMarried: "cmd.admin_marry.already_married",
			Desc:           "cmd.admin_marry.desc",
			Error:          "cmd.admin_marry.error",
			InvalidTarget:  "cmd.admin_marry.invalid_target",
			Success:        "cmd.admin_marry.success",
		},
		Ai: struct {
			Desc MessageID
		}{
			Desc: "cmd.ai.desc",
		},
		AllRests: struct {
			Desc  MessageID
			Empty MessageID
			Item  MessageID
			Title MessageID
		}{
			Desc:  "cmd.all_rests.desc",
			Empty: "cmd.all_rests.empty",
			Item:  "cmd.all_rests.item",
			Title: "cmd.all_rests.title",
		},
		AssignNorm: struct {
			Assigned MessageID
			Desc     MessageID
			Example  MessageID
			NoUsers  MessageID
		}{
			Assigned: "cmd.assign_norm.assigned",
			Desc:     "cmd.assign_norm.desc",
			Example:  "cmd.assign_norm.example",
			NoUsers:  "cmd.assign_norm.no_users",
		},
		Chat: struct {
			DisableEmojis struct {
				Desc    MessageID
				Success MessageID
			}
			DisablePrefixless struct {
				Desc    MessageID
				Success MessageID
			}
			EnableEmojis struct {
				Desc    MessageID
				Success MessageID
			}
			EnablePrefixless struct {
				Desc    MessageID
				Success MessageID
			}
			SetNewbieThreshold struct {
				Desc  MessageID
				Error struct {
					InvalidNumber MessageID
				}
				Success MessageID
			}
			SetNotifyUsernameChangedStatus struct {
				Desc    MessageID
				Success MessageID
			}
			SetPrefix struct {
				Desc  MessageID
				Error struct {
					Empty MessageID
				}
				Success struct {
					Custom  MessageID
					Default MessageID
				}
			}
			SetPrompt struct {
				Desc    MessageID
				Success MessageID
			}
			SetWeekStart struct {
				Desc    MessageID
				Success MessageID
			}
			ShowEmojis struct {
				Desc     MessageID
				Disabled MessageID
				Enabled  MessageID
			}
			ShowNewbieThreshold struct {
				Desc    MessageID
				Success MessageID
			}
			ShowPrefix struct {
				Desc    MessageID
				Success struct {
					Custom  MessageID
					Default MessageID
				}
			}
			ShowPrefixless struct {
				Desc     MessageID
				Disabled MessageID
				Enabled  MessageID
			}
			ShowPrompt struct {
				Desc    MessageID
				Success MessageID
			}
			ShowWeekStart struct {
				Desc    MessageID
				Success MessageID
			}
		}{
			DisableEmojis: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.chat.disable_emojis.desc",
				Success: "cmd.chat.disable_emojis.success",
			},
			DisablePrefixless: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.chat.disable_prefixless.desc",
				Success: "cmd.chat.disable_prefixless.success",
			},
			EnableEmojis: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.chat.enable_emojis.desc",
				Success: "cmd.chat.enable_emojis.success",
			},
			EnablePrefixless: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.chat.enable_prefixless.desc",
				Success: "cmd.chat.enable_prefixless.success",
			},
			SetNewbieThreshold: struct {
				Desc  MessageID
				Error struct {
					InvalidNumber MessageID
				}
				Success MessageID
			}{
				Desc: "cmd.chat.set_newbie_threshold.desc",
				Error: struct {
					InvalidNumber MessageID
				}{
					InvalidNumber: "cmd.chat.set_newbie_threshold.error.invalid_number",
				},
				Success: "cmd.chat.set_newbie_threshold.success",
			},
			SetNotifyUsernameChangedStatus: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.chat.set_notify_username_changed_status.desc",
				Success: "cmd.chat.set_notify_username_changed_status.success",
			},
			SetPrefix: struct {
				Desc  MessageID
				Error struct {
					Empty MessageID
				}
				Success struct {
					Custom  MessageID
					Default MessageID
				}
			}{
				Desc: "cmd.chat.set_prefix.desc",
				Error: struct {
					Empty MessageID
				}{
					Empty: "cmd.chat.set_prefix.error.empty",
				},
				Success: struct {
					Custom  MessageID
					Default MessageID
				}{
					Custom:  "cmd.chat.set_prefix.success.custom",
					Default: "cmd.chat.set_prefix.success.default",
				},
			},
			SetPrompt: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.chat.set_prompt.desc",
				Success: "cmd.chat.set_prompt.success",
			},
			SetWeekStart: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.chat.set_week_start.desc",
				Success: "cmd.chat.set_week_start.success",
			},
			ShowEmojis: struct {
				Desc     MessageID
				Disabled MessageID
				Enabled  MessageID
			}{
				Desc:     "cmd.chat.show_emojis.desc",
				Disabled: "cmd.chat.show_emojis.disabled",
				Enabled:  "cmd.chat.show_emojis.enabled",
			},
			ShowNewbieThreshold: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.chat.show_newbie_threshold.desc",
				Success: "cmd.chat.show_newbie_threshold.success",
			},
			ShowPrefix: struct {
				Desc    MessageID
				Success struct {
					Custom  MessageID
					Default MessageID
				}
			}{
				Desc: "cmd.chat.show_prefix.desc",
				Success: struct {
					Custom  MessageID
					Default MessageID
				}{
					Custom:  "cmd.chat.show_prefix.success.custom",
					Default: "cmd.chat.show_prefix.success.default",
				},
			},
			ShowPrefixless: struct {
				Desc     MessageID
				Disabled MessageID
				Enabled  MessageID
			}{
				Desc:     "cmd.chat.show_prefixless.desc",
				Disabled: "cmd.chat.show_prefixless.disabled",
				Enabled:  "cmd.chat.show_prefixless.enabled",
			},
			ShowPrompt: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.chat.show_prompt.desc",
				Success: "cmd.chat.show_prompt.success",
			},
			ShowWeekStart: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.chat.show_week_start.desc",
				Success: "cmd.chat.show_week_start.success",
			},
		},
		ChatMember: struct {
			Birthday struct {
				Set struct {
					Desc    MessageID
					Success MessageID
				}
			}
			DeleteDescription struct {
				Desc    MessageID
				Success MessageID
			}
			RemoveEmoji struct {
				Desc    MessageID
				Success MessageID
			}
			SetDescription struct {
				Desc    MessageID
				Success MessageID
				TooLong MessageID
			}
			SetEmoji struct {
				Desc    MessageID
				Success MessageID
			}
			ShowEmoji struct {
				Desc    MessageID
				NoEmoji MessageID
				Success MessageID
			}
			Update struct {
				Desc    MessageID
				Success MessageID
			}
		}{
			Birthday: struct {
				Set struct {
					Desc    MessageID
					Success MessageID
				}
			}{
				Set: struct {
					Desc    MessageID
					Success MessageID
				}{
					Desc:    "cmd.chat_member.birthday.set.desc",
					Success: "cmd.chat_member.birthday.set.success",
				},
			},
			DeleteDescription: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.chat_member.delete_description.desc",
				Success: "cmd.chat_member.delete_description.success",
			},
			RemoveEmoji: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.chat_member.remove_emoji.desc",
				Success: "cmd.chat_member.remove_emoji.success",
			},
			SetDescription: struct {
				Desc    MessageID
				Success MessageID
				TooLong MessageID
			}{
				Desc:    "cmd.chat_member.set_description.desc",
				Success: "cmd.chat_member.set_description.success",
				TooLong: "cmd.chat_member.set_description.too_long",
			},
			SetEmoji: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.chat_member.set_emoji.desc",
				Success: "cmd.chat_member.set_emoji.success",
			},
			ShowEmoji: struct {
				Desc    MessageID
				NoEmoji MessageID
				Success MessageID
			}{
				Desc:    "cmd.chat_member.show_emoji.desc",
				NoEmoji: "cmd.chat_member.show_emoji.no_emoji",
				Success: "cmd.chat_member.show_emoji.success",
			},
			Update: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.chat_member.update.desc",
				Success: "cmd.chat_member.update.success",
			},
		},
		Crocodile: struct {
			AlreadyStarted MessageID
			Button         struct {
				BecomeHost MessageID
				Finish     MessageID
				Next       MessageID
				ShowWord   MessageID
			}
			Callback struct {
				Finished MessageID
				Host     MessageID
				Next     MessageID
				Word     MessageID
			}
			Continued MessageID
			Desc      MessageID
			Error     struct {
				AlreadyStarted MessageID
				Finish         MessageID
				NextWord       MessageID
				NotHost        MessageID
				NotStarted     MessageID
				Start          MessageID
			}
			Game struct {
				Ended MessageID
			}
			Host struct {
				Left MessageID
			}
			Skip struct {
				Success MessageID
			}
			Started             MessageID
			StartedSkippedWords MessageID
			Stop                struct {
				Desc MessageID
			}
			Stopped MessageID
			Timeout struct {
				Message MessageID
			}
			Winner MessageID
			Word   MessageID
		}{
			AlreadyStarted: "cmd.crocodile.already_started",
			Button: struct {
				BecomeHost MessageID
				Finish     MessageID
				Next       MessageID
				ShowWord   MessageID
			}{
				BecomeHost: "cmd.crocodile.button.become_host",
				Finish:     "cmd.crocodile.button.finish",
				Next:       "cmd.crocodile.button.next",
				ShowWord:   "cmd.crocodile.button.show_word",
			},
			Callback: struct {
				Finished MessageID
				Host     MessageID
				Next     MessageID
				Word     MessageID
			}{
				Finished: "cmd.crocodile.callback.finished",
				Host:     "cmd.crocodile.callback.host",
				Next:     "cmd.crocodile.callback.next",
				Word:     "cmd.crocodile.callback.word",
			},
			Continued: "cmd.crocodile.continued",
			Desc:      "cmd.crocodile.desc",
			Error: struct {
				AlreadyStarted MessageID
				Finish         MessageID
				NextWord       MessageID
				NotHost        MessageID
				NotStarted     MessageID
				Start          MessageID
			}{
				AlreadyStarted: "cmd.crocodile.error.already_started",
				Finish:         "cmd.crocodile.error.finish",
				NextWord:       "cmd.crocodile.error.next_word",
				NotHost:        "cmd.crocodile.error.not_host",
				NotStarted:     "cmd.crocodile.error.not_started",
				Start:          "cmd.crocodile.error.start",
			},
			Game: struct {
				Ended MessageID
			}{
				Ended: "cmd.crocodile.game.ended",
			},
			Host: struct {
				Left MessageID
			}{
				Left: "cmd.crocodile.host.left",
			},
			Skip: struct {
				Success MessageID
			}{
				Success: "cmd.crocodile.skip.success",
			},
			Started:             "cmd.crocodile.started",
			StartedSkippedWords: "cmd.crocodile.started_skipped_words",
			Stop: struct {
				Desc MessageID
			}{
				Desc: "cmd.crocodile.stop.desc",
			},
			Stopped: "cmd.crocodile.stopped",
			Timeout: struct {
				Message MessageID
			}{
				Message: "cmd.crocodile.timeout.message",
			},
			Winner: "cmd.crocodile.winner",
			Word:   "cmd.crocodile.word",
		},
		DelRp: struct {
			Desc    MessageID
			Success MessageID
		}{
			Desc:    "cmd.del_rp.desc",
			Success: "cmd.del_rp.success",
		},
		DeleteNorm: struct {
			Deleted            MessageID
			Desc               MessageID
			ErrNothingToDelete MessageID
			Example            MessageID
		}{
			Deleted:            "cmd.delete_norm.deleted",
			Desc:               "cmd.delete_norm.desc",
			ErrNothingToDelete: "cmd.delete_norm.err_nothing_to_delete",
			Example:            "cmd.delete_norm.example",
		},
		DisablePolygamy: struct {
			Desc    MessageID
			Success MessageID
		}{
			Desc:    "cmd.disable_polygamy.desc",
			Success: "cmd.disable_polygamy.success",
		},
		Divorce: struct {
			Announce         MessageID
			AnnouncePolygamy MessageID
			Desc             MessageID
			Error            struct {
				Divorce         MessageID
				NoMarriage      MessageID
				NotYourMarriage MessageID
			}
			Self MessageID
		}{
			Announce:         "cmd.divorce.announce",
			AnnouncePolygamy: "cmd.divorce.announce_polygamy",
			Desc:             "cmd.divorce.desc",
			Error: struct {
				Divorce         MessageID
				NoMarriage      MessageID
				NotYourMarriage MessageID
			}{
				Divorce:         "cmd.divorce.error.divorce",
				NoMarriage:      "cmd.divorce.error.no_marriage",
				NotYourMarriage: "cmd.divorce.error.not_your_marriage",
			},
			Self: "cmd.divorce.self",
		},
		EnablePolygamy: struct {
			Desc    MessageID
			Success MessageID
		}{
			Desc:    "cmd.enable_polygamy.desc",
			Success: "cmd.enable_polygamy.success",
		},
		EndRest: struct {
			Desc          MessageID
			Ended         MessageID
			EndedSelf     MessageID
			NotInRest     MessageID
			NotInRestSelf MessageID
		}{
			Desc:          "cmd.end_rest.desc",
			Ended:         "cmd.end_rest.ended",
			EndedSelf:     "cmd.end_rest.ended_self",
			NotInRest:     "cmd.end_rest.not_in_rest",
			NotInRestSelf: "cmd.end_rest.not_in_rest_self",
		},
		FakeLeave: struct {
			Desc MessageID
		}{
			Desc: "cmd.fake_leave.desc",
		},
		Help: struct {
			Access         MessageID
			AliasesLabel   MessageID
			Body           MessageID
			ButtonBack     MessageID
			ButtonCommands MessageID
			ChooseCategory MessageID
			Desc           MessageID
			DisableInfo    MessageID
			EnableInfo     MessageID
			Examples       MessageID
			Page           MessageID
			Syntax         MessageID
		}{
			Access:         "cmd.help.access",
			AliasesLabel:   "cmd.help.aliases_label",
			Body:           "cmd.help.body",
			ButtonBack:     "cmd.help.button_back",
			ButtonCommands: "cmd.help.button_commands",
			ChooseCategory: "cmd.help.choose_category",
			Desc:           "cmd.help.desc",
			DisableInfo:    "cmd.help.disable_info",
			EnableInfo:     "cmd.help.enable_info",
			Examples:       "cmd.help.examples",
			Page:           "cmd.help.page",
			Syntax:         "cmd.help.syntax",
		},
		HelpCommand: struct {
			Desc MessageID
		}{
			Desc: "cmd.help_command.desc",
		},
		Inactive: struct {
			Desc            MessageID
			EmptyList       MessageID
			Never           MessageID
			NoUsersToSummon MessageID
			SummonButton    MessageID
			Title           MessageID
			User            MessageID
		}{
			Desc:            "cmd.inactive.desc",
			EmptyList:       "cmd.inactive.empty_list",
			Never:           "cmd.inactive.never",
			NoUsersToSummon: "cmd.inactive.no_users_to_summon",
			SummonButton:    "cmd.inactive.summon_button",
			Title:           "cmd.inactive.title",
			User:            "cmd.inactive.user",
		},
		ListNorms: struct {
			Desc  MessageID
			Empty MessageID
			Item  MessageID
			Title MessageID
		}{
			Desc:  "cmd.list_norms.desc",
			Empty: "cmd.list_norms.empty",
			Item:  "cmd.list_norms.item",
			Title: "cmd.list_norms.title",
		},
		ListRewards: struct {
			Desc      MessageID
			Given     MessageID
			NoRewards MessageID
			Title     MessageID
		}{
			Desc:      "cmd.list_rewards.desc",
			Given:     "cmd.list_rewards.given",
			NoRewards: "cmd.list_rewards.no_rewards",
			Title:     "cmd.list_rewards.title",
		},
		ListRp: struct {
			Desc  MessageID
			Empty MessageID
			Title MessageID
		}{
			Desc:  "cmd.list_rp.desc",
			Empty: "cmd.list_rp.empty",
			Title: "cmd.list_rp.title",
		},
		Manage: struct {
			Desc     MessageID
			NoChats  MessageID
			NotFound MessageID
			Select   MessageID
			Selected MessageID
			Success  MessageID
			Untitled MessageID
		}{
			Desc:     "cmd.manage.desc",
			NoChats:  "cmd.manage.no_chats",
			NotFound: "cmd.manage.not_found",
			Select:   "cmd.manage.select",
			Selected: "cmd.manage.selected",
			Success:  "cmd.manage.success",
			Untitled: "cmd.manage.untitled",
		},
		Marriage: struct {
			Active     MessageID
			ActiveMany MessageID
			Desc       MessageID
			Error      struct {
				Load   MessageID
				Reject MessageID
			}
			None MessageID
			Self MessageID
		}{
			Active:     "cmd.marriage.active",
			ActiveMany: "cmd.marriage.active_many",
			Desc:       "cmd.marriage.desc",
			Error: struct {
				Load   MessageID
				Reject MessageID
			}{
				Load:   "cmd.marriage.error.load",
				Reject: "cmd.marriage.error.reject",
			},
			None: "cmd.marriage.none",
			Self: "cmd.marriage.self",
		},
		Marriages: struct {
			Category struct {
				Calico    MessageID
				CastIron  MessageID
				Copper    MessageID
				Faience   MessageID
				Green     MessageID
				Leather   MessageID
				Linen     MessageID
				Newlyweds MessageID
				Paper     MessageID
				Rose      MessageID
				Tin       MessageID
				Unknown   MessageID
				Wooden    MessageID
				Years     MessageID
			}
			Desc  MessageID
			Error struct {
				Load MessageID
			}
			None     MessageID
			Together MessageID
		}{
			Category: struct {
				Calico    MessageID
				CastIron  MessageID
				Copper    MessageID
				Faience   MessageID
				Green     MessageID
				Leather   MessageID
				Linen     MessageID
				Newlyweds MessageID
				Paper     MessageID
				Rose      MessageID
				Tin       MessageID
				Unknown   MessageID
				Wooden    MessageID
				Years     MessageID
			}{
				Calico:    "cmd.marriages.category.calico",
				CastIron:  "cmd.marriages.category.cast_iron",
				Copper:    "cmd.marriages.category.copper",
				Faience:   "cmd.marriages.category.faience",
				Green:     "cmd.marriages.category.green",
				Leather:   "cmd.marriages.category.leather",
				Linen:     "cmd.marriages.category.linen",
				Newlyweds: "cmd.marriages.category.newlyweds",
				Paper:     "cmd.marriages.category.paper",
				Rose:      "cmd.marriages.category.rose",
				Tin:       "cmd.marriages.category.tin",
				Unknown:   "cmd.marriages.category.unknown",
				Wooden:    "cmd.marriages.category.wooden",
				Years:     "cmd.marriages.category.years",
			},
			Desc: "cmd.marriages.desc",
			Error: struct {
				Load MessageID
			}{
				Load: "cmd.marriages.error.load",
			},
			None:     "cmd.marriages.none",
			Together: "cmd.marriages.together",
		},
		Marry: struct {
			Accepted             MessageID
			Announce1            MessageID
			Announce2            MessageID
			Announce3            MessageID
			Announce4            MessageID
			Announce5            MessageID
			Announce6            MessageID
			AnnouncePolygamy1    MessageID
			AnnouncePolygamy2    MessageID
			AnnouncePolygamy3    MessageID
			AnnouncePolygamy4    MessageID
			AnnouncePolygamy5    MessageID
			AnnouncePolygamy6    MessageID
			AutoAccepted         MessageID
			AutoAcceptedPolygamy MessageID
			Bot                  MessageID
			BotSelf              MessageID
			Button               struct {
				Accept MessageID
				Reject MessageID
			}
			Callback struct {
				Accepted MessageID
				Rejected MessageID
			}
			Desc           MessageID
			Direct         MessageID
			DirectPolygamy MessageID
			Error          struct {
				Accept         MessageID
				AlreadyMarried MessageID
				InvalidTarget  MessageID
				Reject         MessageID
				RequestExists  MessageID
			}
			Rejected        MessageID
			Request         MessageID
			RequestPolygamy MessageID
			Self            MessageID
		}{
			Accepted:             "cmd.marry.accepted",
			Announce1:            "cmd.marry.announce_1",
			Announce2:            "cmd.marry.announce_2",
			Announce3:            "cmd.marry.announce_3",
			Announce4:            "cmd.marry.announce_4",
			Announce5:            "cmd.marry.announce_5",
			Announce6:            "cmd.marry.announce_6",
			AnnouncePolygamy1:    "cmd.marry.announce_polygamy_1",
			AnnouncePolygamy2:    "cmd.marry.announce_polygamy_2",
			AnnouncePolygamy3:    "cmd.marry.announce_polygamy_3",
			AnnouncePolygamy4:    "cmd.marry.announce_polygamy_4",
			AnnouncePolygamy5:    "cmd.marry.announce_polygamy_5",
			AnnouncePolygamy6:    "cmd.marry.announce_polygamy_6",
			AutoAccepted:         "cmd.marry.auto_accepted",
			AutoAcceptedPolygamy: "cmd.marry.auto_accepted_polygamy",
			Bot:                  "cmd.marry.bot",
			BotSelf:              "cmd.marry.bot_self",
			Button: struct {
				Accept MessageID
				Reject MessageID
			}{
				Accept: "cmd.marry.button.accept",
				Reject: "cmd.marry.button.reject",
			},
			Callback: struct {
				Accepted MessageID
				Rejected MessageID
			}{
				Accepted: "cmd.marry.callback.accepted",
				Rejected: "cmd.marry.callback.rejected",
			},
			Desc:           "cmd.marry.desc",
			Direct:         "cmd.marry.direct",
			DirectPolygamy: "cmd.marry.direct_polygamy",
			Error: struct {
				Accept         MessageID
				AlreadyMarried MessageID
				InvalidTarget  MessageID
				Reject         MessageID
				RequestExists  MessageID
			}{
				Accept:         "cmd.marry.error.accept",
				AlreadyMarried: "cmd.marry.error.already_married",
				InvalidTarget:  "cmd.marry.error.invalid_target",
				Reject:         "cmd.marry.error.reject",
				RequestExists:  "cmd.marry.error.request_exists",
			},
			Rejected:        "cmd.marry.rejected",
			Request:         "cmd.marry.request",
			RequestPolygamy: "cmd.marry.request_polygamy",
			Self:            "cmd.marry.self",
		},
		Moderation: struct {
			Actions struct {
				Ban  MessageID
				Kick MessageID
				Mute MessageID
				Warn MessageID
			}
			Ban struct {
				Desc MessageID
			}
			Chatoff struct {
				Desc MessageID
			}
			Chaton struct {
				Desc MessageID
			}
			ClearWarns struct {
				Desc    MessageID
				Success MessageID
			}
			DeleteMessage struct {
				Desc MessageID
			}
			Demote struct {
				Desc MessageID
			}
			Kick struct {
				Desc MessageID
			}
			ListAdmins struct {
				Desc   MessageID
				Empty  MessageID
				Header MessageID
			}
			ListRoles struct {
				Desc   MessageID
				Empty  MessageID
				Header MessageID
			}
			MaxWarns struct {
				Desc MessageID
				Show MessageID
			}
			Mute struct {
				Desc MessageID
			}
			Promote struct {
				Desc MessageID
			}
			RemoveAdmin struct {
				CantModerate MessageID
				Desc         MessageID
				Success      MessageID
			}
			Rights struct {
				CanChangeInfo      MessageID
				CanDeleteMessages  MessageID
				CanInviteUsers     MessageID
				CanManageChat      MessageID
				CanManageTopics    MessageID
				CanPinMessages     MessageID
				CanPromoteMembers  MessageID
				CanRestrictMembers MessageID
				UpdateFailed       MessageID
				Updated            MessageID
			}
			SetMaxWarns struct {
				Desc MessageID
				Set  MessageID
			}
			SetRole struct {
				ChatAdmin   MessageID
				ChatCreator MessageID
				Desc        MessageID
				NoRights    MessageID
				Set         MessageID
			}
			SetRoleAdmin struct {
				ChatAdmin   MessageID
				ChatCreator MessageID
				Desc        MessageID
				NoRights    MessageID
			}
			SetStatus struct {
				CantModerate  MessageID
				Desc          MessageID
				InvalidStatus MessageID
				Success       MessageID
			}
			ShowWarns struct {
				Desc    MessageID
				Empty   MessageID
				Expires MessageID
				Header  MessageID
				Item    MessageID
				Reason  MessageID
			}
			Templates struct {
				Action    MessageID
				Forever   MessageID
				Moderator MessageID
				Reason    MessageID
				Until     MessageID
				Warns     MessageID
			}
			Unban struct {
				Desc     MessageID
				Unbanned MessageID
			}
			Unwarn struct {
				Desc    MessageID
				Success MessageID
			}
			Warn struct {
				Desc MessageID
			}
			WarnList struct {
				Desc    MessageID
				Empty   MessageID
				Expires MessageID
				Header  MessageID
				Item    MessageID
				Reason  MessageID
			}
		}{
			Actions: struct {
				Ban  MessageID
				Kick MessageID
				Mute MessageID
				Warn MessageID
			}{
				Ban:  "cmd.moderation.actions.ban",
				Kick: "cmd.moderation.actions.kick",
				Mute: "cmd.moderation.actions.mute",
				Warn: "cmd.moderation.actions.warn",
			},
			Ban: struct {
				Desc MessageID
			}{
				Desc: "cmd.moderation.ban.desc",
			},
			Chatoff: struct {
				Desc MessageID
			}{
				Desc: "cmd.moderation.chatoff.desc",
			},
			Chaton: struct {
				Desc MessageID
			}{
				Desc: "cmd.moderation.chaton.desc",
			},
			ClearWarns: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.moderation.clear_warns.desc",
				Success: "cmd.moderation.clear_warns.success",
			},
			DeleteMessage: struct {
				Desc MessageID
			}{
				Desc: "cmd.moderation.delete_message.desc",
			},
			Demote: struct {
				Desc MessageID
			}{
				Desc: "cmd.moderation.demote.desc",
			},
			Kick: struct {
				Desc MessageID
			}{
				Desc: "cmd.moderation.kick.desc",
			},
			ListAdmins: struct {
				Desc   MessageID
				Empty  MessageID
				Header MessageID
			}{
				Desc:   "cmd.moderation.list_admins.desc",
				Empty:  "cmd.moderation.list_admins.empty",
				Header: "cmd.moderation.list_admins.header",
			},
			ListRoles: struct {
				Desc   MessageID
				Empty  MessageID
				Header MessageID
			}{
				Desc:   "cmd.moderation.list_roles.desc",
				Empty:  "cmd.moderation.list_roles.empty",
				Header: "cmd.moderation.list_roles.header",
			},
			MaxWarns: struct {
				Desc MessageID
				Show MessageID
			}{
				Desc: "cmd.moderation.max_warns.desc",
				Show: "cmd.moderation.max_warns.show",
			},
			Mute: struct {
				Desc MessageID
			}{
				Desc: "cmd.moderation.mute.desc",
			},
			Promote: struct {
				Desc MessageID
			}{
				Desc: "cmd.moderation.promote.desc",
			},
			RemoveAdmin: struct {
				CantModerate MessageID
				Desc         MessageID
				Success      MessageID
			}{
				CantModerate: "cmd.moderation.remove_admin.cant_moderate",
				Desc:         "cmd.moderation.remove_admin.desc",
				Success:      "cmd.moderation.remove_admin.success",
			},
			Rights: struct {
				CanChangeInfo      MessageID
				CanDeleteMessages  MessageID
				CanInviteUsers     MessageID
				CanManageChat      MessageID
				CanManageTopics    MessageID
				CanPinMessages     MessageID
				CanPromoteMembers  MessageID
				CanRestrictMembers MessageID
				UpdateFailed       MessageID
				Updated            MessageID
			}{
				CanChangeInfo:      "cmd.moderation.rights.can_change_info",
				CanDeleteMessages:  "cmd.moderation.rights.can_delete_messages",
				CanInviteUsers:     "cmd.moderation.rights.can_invite_users",
				CanManageChat:      "cmd.moderation.rights.can_manage_chat",
				CanManageTopics:    "cmd.moderation.rights.can_manage_topics",
				CanPinMessages:     "cmd.moderation.rights.can_pin_messages",
				CanPromoteMembers:  "cmd.moderation.rights.can_promote_members",
				CanRestrictMembers: "cmd.moderation.rights.can_restrict_members",
				UpdateFailed:       "cmd.moderation.rights.update_failed",
				Updated:            "cmd.moderation.rights.updated",
			},
			SetMaxWarns: struct {
				Desc MessageID
				Set  MessageID
			}{
				Desc: "cmd.moderation.set_max_warns.desc",
				Set:  "cmd.moderation.set_max_warns.set",
			},
			SetRole: struct {
				ChatAdmin   MessageID
				ChatCreator MessageID
				Desc        MessageID
				NoRights    MessageID
				Set         MessageID
			}{
				ChatAdmin:   "cmd.moderation.set_role.chat_admin",
				ChatCreator: "cmd.moderation.set_role.chat_creator",
				Desc:        "cmd.moderation.set_role.desc",
				NoRights:    "cmd.moderation.set_role.no_rights",
				Set:         "cmd.moderation.set_role.set",
			},
			SetRoleAdmin: struct {
				ChatAdmin   MessageID
				ChatCreator MessageID
				Desc        MessageID
				NoRights    MessageID
			}{
				ChatAdmin:   "cmd.moderation.set_role_admin.chat_admin",
				ChatCreator: "cmd.moderation.set_role_admin.chat_creator",
				Desc:        "cmd.moderation.set_role_admin.desc",
				NoRights:    "cmd.moderation.set_role_admin.no_rights",
			},
			SetStatus: struct {
				CantModerate  MessageID
				Desc          MessageID
				InvalidStatus MessageID
				Success       MessageID
			}{
				CantModerate:  "cmd.moderation.set_status.cant_moderate",
				Desc:          "cmd.moderation.set_status.desc",
				InvalidStatus: "cmd.moderation.set_status.invalid_status",
				Success:       "cmd.moderation.set_status.success",
			},
			ShowWarns: struct {
				Desc    MessageID
				Empty   MessageID
				Expires MessageID
				Header  MessageID
				Item    MessageID
				Reason  MessageID
			}{
				Desc:    "cmd.moderation.show_warns.desc",
				Empty:   "cmd.moderation.show_warns.empty",
				Expires: "cmd.moderation.show_warns.expires",
				Header:  "cmd.moderation.show_warns.header",
				Item:    "cmd.moderation.show_warns.item",
				Reason:  "cmd.moderation.show_warns.reason",
			},
			Templates: struct {
				Action    MessageID
				Forever   MessageID
				Moderator MessageID
				Reason    MessageID
				Until     MessageID
				Warns     MessageID
			}{
				Action:    "cmd.moderation.templates.action",
				Forever:   "cmd.moderation.templates.forever",
				Moderator: "cmd.moderation.templates.moderator",
				Reason:    "cmd.moderation.templates.reason",
				Until:     "cmd.moderation.templates.until",
				Warns:     "cmd.moderation.templates.warns",
			},
			Unban: struct {
				Desc     MessageID
				Unbanned MessageID
			}{
				Desc:     "cmd.moderation.unban.desc",
				Unbanned: "cmd.moderation.unban.unbanned",
			},
			Unwarn: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.moderation.unwarn.desc",
				Success: "cmd.moderation.unwarn.success",
			},
			Warn: struct {
				Desc MessageID
			}{
				Desc: "cmd.moderation.warn.desc",
			},
			WarnList: struct {
				Desc    MessageID
				Empty   MessageID
				Expires MessageID
				Header  MessageID
				Item    MessageID
				Reason  MessageID
			}{
				Desc:    "cmd.moderation.warn_list.desc",
				Empty:   "cmd.moderation.warn_list.empty",
				Expires: "cmd.moderation.warn_list.expires",
				Header:  "cmd.moderation.warn_list.header",
				Item:    "cmd.moderation.warn_list.item",
				Reason:  "cmd.moderation.warn_list.reason",
			},
		},
		Permission: struct {
			Set struct {
				CannotAllowMembers MessageID
				CannotDisable      MessageID
				Desc               MessageID
				Success            MessageID
				UnknownCommand     MessageID
			}
			Show struct {
				Desc    MessageID
				Success MessageID
			}
		}{
			Set: struct {
				CannotAllowMembers MessageID
				CannotDisable      MessageID
				Desc               MessageID
				Success            MessageID
				UnknownCommand     MessageID
			}{
				CannotAllowMembers: "cmd.permission.set.cannot_allow_members",
				CannotDisable:      "cmd.permission.set.cannot_disable",
				Desc:               "cmd.permission.set.desc",
				Success:            "cmd.permission.set.success",
				UnknownCommand:     "cmd.permission.set.unknown_command",
			},
			Show: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.permission.show.desc",
				Success: "cmd.permission.show.success",
			},
		},
		Profile: struct {
			Activity          MessageID
			AllNormsPassed    MessageID
			Desc              MessageID
			ExampleDate       MessageID
			ExampleDuration   MessageID
			MemberPeriod      MessageID
			MemberSince       MessageID
			NewbieExempt      MessageID
			NormFailed        MessageID
			NormPassed        MessageID
			NormsStatusHeader MessageID
			RestExempt        MessageID
			RestUntil         MessageID
			Rewards           MessageID
			RewardsButton     MessageID
			Title             MessageID
			TotalMessages     MessageID
		}{
			Activity:          "cmd.profile.activity",
			AllNormsPassed:    "cmd.profile.all_norms_passed",
			Desc:              "cmd.profile.desc",
			ExampleDate:       "cmd.profile.example_date",
			ExampleDuration:   "cmd.profile.example_duration",
			MemberPeriod:      "cmd.profile.member_period",
			MemberSince:       "cmd.profile.member_since",
			NewbieExempt:      "cmd.profile.newbie_exempt",
			NormFailed:        "cmd.profile.norm_failed",
			NormPassed:        "cmd.profile.norm_passed",
			NormsStatusHeader: "cmd.profile.norms_status_header",
			RestExempt:        "cmd.profile.rest_exempt",
			RestUntil:         "cmd.profile.rest_until",
			Rewards:           "cmd.profile.rewards",
			RewardsButton:     "cmd.profile.rewards_button",
			Title:             "cmd.profile.title",
			TotalMessages:     "cmd.profile.total_messages",
		},
		Rest: struct {
			Desc       MessageID
			Info       MessageID
			InfoReason MessageID
			NoRest     MessageID
			Set        MessageID
			SetReason  MessageID
		}{
			Desc:       "cmd.rest.desc",
			Info:       "cmd.rest.info",
			InfoReason: "cmd.rest.info_reason",
			NoRest:     "cmd.rest.no_rest",
			Set:        "cmd.rest.set",
			SetReason:  "cmd.rest.set_reason",
		},
		RestRequest: struct {
			ApproveButton MessageID
			Approved      MessageID
			ApprovedShort MessageID
			Created       MessageID
			Empty         MessageID
			Item          MessageID
			NoRequest     MessageID
			RejectButton  MessageID
			Rejected      MessageID
			Text          MessageID
			TextReason    MessageID
			Title         MessageID
		}{
			ApproveButton: "cmd.rest_request.approve_button",
			Approved:      "cmd.rest_request.approved",
			ApprovedShort: "cmd.rest_request.approved_short",
			Created:       "cmd.rest_request.created",
			Empty:         "cmd.rest_request.empty",
			Item:          "cmd.rest_request.item",
			NoRequest:     "cmd.rest_request.no_request",
			RejectButton:  "cmd.rest_request.reject_button",
			Rejected:      "cmd.rest_request.rejected",
			Text:          "cmd.rest_request.text",
			TextReason:    "cmd.rest_request.text_reason",
			Title:         "cmd.rest_request.title",
		},
		Rests: struct {
			Delete struct {
				Deleted       MessageID
				DeletedActive MessageID
				Desc          MessageID
			}
			Desc              MessageID
			HistoryEmpty      MessageID
			HistoryItem       MessageID
			HistoryItemReason MessageID
			HistoryTitle      MessageID
			HistoryTotal      MessageID
		}{
			Delete: struct {
				Deleted       MessageID
				DeletedActive MessageID
				Desc          MessageID
			}{
				Deleted:       "cmd.rests.delete.deleted",
				DeletedActive: "cmd.rests.delete.deleted_active",
				Desc:          "cmd.rests.delete.desc",
			},
			Desc:              "cmd.rests.desc",
			HistoryEmpty:      "cmd.rests.history_empty",
			HistoryItem:       "cmd.rests.history_item",
			HistoryItemReason: "cmd.rests.history_item_reason",
			HistoryTitle:      "cmd.rests.history_title",
			HistoryTotal:      "cmd.rests.history_total",
		},
		Reward: struct {
			Desc    MessageID
			Success MessageID
		}{
			Desc:    "cmd.reward.desc",
			Success: "cmd.reward.success",
		},
		Roles: struct {
			Free struct {
				Desc    MessageID
				Success MessageID
			}
			Genshin struct {
				Desc    MessageID
				Success MessageID
			}
			Reserve struct {
				Desc    MessageID
				Success MessageID
			}
		}{
			Free: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.roles.free.desc",
				Success: "cmd.roles.free.success",
			},
			Genshin: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.roles.genshin.desc",
				Success: "cmd.roles.genshin.success",
			},
			Reserve: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.roles.reserve.desc",
				Success: "cmd.roles.reserve.success",
			},
		},
		Rp: struct {
			ChooseGender MessageID
			GenderFemale MessageID
			GenderMale   MessageID
			Speech       MessageID
		}{
			ChooseGender: "cmd.rp.choose_gender",
			GenderFemale: "cmd.rp.gender_female",
			GenderMale:   "cmd.rp.gender_male",
			Speech:       "cmd.rp.speech",
		},
		Ship: struct {
			Bot1    MessageID
			Bot2    MessageID
			Bot3    MessageID
			Bot4    MessageID
			Bot5    MessageID
			Bot6    MessageID
			Bot7    MessageID
			Bot8    MessageID
			BotBot1 MessageID
			BotBot2 MessageID
			BotBot3 MessageID
			BotBot4 MessageID
			BotBot5 MessageID
			BotBot6 MessageID
			BotBot7 MessageID
			BotBot8 MessageID
			Desc    MessageID
			None    MessageID
			Normal1 MessageID
			Normal2 MessageID
			Normal3 MessageID
			Normal4 MessageID
			Normal5 MessageID
			Normal6 MessageID
			Normal7 MessageID
			Normal8 MessageID
			Self1   MessageID
			Self2   MessageID
			Self3   MessageID
			Self4   MessageID
			Self5   MessageID
			Self6   MessageID
			Self7   MessageID
			Self8   MessageID
		}{
			Bot1:    "cmd.ship.bot_1",
			Bot2:    "cmd.ship.bot_2",
			Bot3:    "cmd.ship.bot_3",
			Bot4:    "cmd.ship.bot_4",
			Bot5:    "cmd.ship.bot_5",
			Bot6:    "cmd.ship.bot_6",
			Bot7:    "cmd.ship.bot_7",
			Bot8:    "cmd.ship.bot_8",
			BotBot1: "cmd.ship.bot_bot_1",
			BotBot2: "cmd.ship.bot_bot_2",
			BotBot3: "cmd.ship.bot_bot_3",
			BotBot4: "cmd.ship.bot_bot_4",
			BotBot5: "cmd.ship.bot_bot_5",
			BotBot6: "cmd.ship.bot_bot_6",
			BotBot7: "cmd.ship.bot_bot_7",
			BotBot8: "cmd.ship.bot_bot_8",
			Desc:    "cmd.ship.desc",
			None:    "cmd.ship.none",
			Normal1: "cmd.ship.normal_1",
			Normal2: "cmd.ship.normal_2",
			Normal3: "cmd.ship.normal_3",
			Normal4: "cmd.ship.normal_4",
			Normal5: "cmd.ship.normal_5",
			Normal6: "cmd.ship.normal_6",
			Normal7: "cmd.ship.normal_7",
			Normal8: "cmd.ship.normal_8",
			Self1:   "cmd.ship.self_1",
			Self2:   "cmd.ship.self_2",
			Self3:   "cmd.ship.self_3",
			Self4:   "cmd.ship.self_4",
			Self5:   "cmd.ship.self_5",
			Self6:   "cmd.ship.self_6",
			Self7:   "cmd.ship.self_7",
			Self8:   "cmd.ship.self_8",
		},
		ShowNorm: struct {
			AllMembers MessageID
			Body       MessageID
			Desc       MessageID
			Example    MessageID
			Members    MessageID
			NotFound   MessageID
		}{
			AllMembers: "cmd.show_norm.all_members",
			Body:       "cmd.show_norm.body",
			Desc:       "cmd.show_norm.desc",
			Example:    "cmd.show_norm.example",
			Members:    "cmd.show_norm.members",
			NotFound:   "cmd.show_norm.not_found",
		},
		Stats: struct {
			AllPassed        MessageID
			AskForNormName   MessageID
			AskForSummonText MessageID
			Desc             MessageID
			EmptyList        MessageID
			ExampleDate      MessageID
			ExampleDuration  MessageID
			Failed           MessageID
			Newbies          MessageID
			NobodyToSummon   MessageID
			NormNotFound     MessageID
			NormTitle        MessageID
			Passed           MessageID
			Resting          MessageID
			SummonNoNorm     MessageID
			Title            MessageID
			TotalMessages    MessageID
			UserFailed       MessageID
			UserPassed       MessageID
		}{
			AllPassed:        "cmd.stats.all_passed",
			AskForNormName:   "cmd.stats.ask_for_norm_name",
			AskForSummonText: "cmd.stats.ask_for_summon_text",
			Desc:             "cmd.stats.desc",
			EmptyList:        "cmd.stats.empty_list",
			ExampleDate:      "cmd.stats.example_date",
			ExampleDuration:  "cmd.stats.example_duration",
			Failed:           "cmd.stats.failed",
			Newbies:          "cmd.stats.newbies",
			NobodyToSummon:   "cmd.stats.nobody_to_summon",
			NormNotFound:     "cmd.stats.norm_not_found",
			NormTitle:        "cmd.stats.norm_title",
			Passed:           "cmd.stats.passed",
			Resting:          "cmd.stats.resting",
			SummonNoNorm:     "cmd.stats.summon_no_norm",
			Title:            "cmd.stats.title",
			TotalMessages:    "cmd.stats.total_messages",
			UserFailed:       "cmd.stats.user_failed",
			UserPassed:       "cmd.stats.user_passed",
		},
		StopCrocodile: struct {
			Desc MessageID
		}{
			Desc: "cmd.stop_crocodile.desc",
		},
		Summon: struct {
			AlreadyRunning MessageID
			Completed      MessageID
			Confirm        struct {
				Canceled             MessageID
				Disabled             MessageID
				No                   MessageID
				OnlyInitiatorCancel  MessageID
				OnlyInitiatorConfirm MessageID
				Text                 MessageID
				Yes                  MessageID
				YesAndDisable        MessageID
			}
			Desc      MessageID
			EnterText MessageID
			Reg       struct {
				Desc MessageID
				Set  MessageID
			}
			Style struct {
				Desc   MessageID
				Emoji  MessageID
				Name   MessageID
				Role   MessageID
				Text   MessageID
				Toggle struct {
					Desc MessageID
				}
			}
			Unreg struct {
				Desc MessageID
				Set  MessageID
			}
		}{
			AlreadyRunning: "cmd.summon.already_running",
			Completed:      "cmd.summon.completed",
			Confirm: struct {
				Canceled             MessageID
				Disabled             MessageID
				No                   MessageID
				OnlyInitiatorCancel  MessageID
				OnlyInitiatorConfirm MessageID
				Text                 MessageID
				Yes                  MessageID
				YesAndDisable        MessageID
			}{
				Canceled:             "cmd.summon.confirm.canceled",
				Disabled:             "cmd.summon.confirm.disabled",
				No:                   "cmd.summon.confirm.no",
				OnlyInitiatorCancel:  "cmd.summon.confirm.only_initiator_cancel",
				OnlyInitiatorConfirm: "cmd.summon.confirm.only_initiator_confirm",
				Text:                 "cmd.summon.confirm.text",
				Yes:                  "cmd.summon.confirm.yes",
				YesAndDisable:        "cmd.summon.confirm.yes_and_disable",
			},
			Desc:      "cmd.summon.desc",
			EnterText: "cmd.summon.enter_text",
			Reg: struct {
				Desc MessageID
				Set  MessageID
			}{
				Desc: "cmd.summon.reg.desc",
				Set:  "cmd.summon.reg.set",
			},
			Style: struct {
				Desc   MessageID
				Emoji  MessageID
				Name   MessageID
				Role   MessageID
				Text   MessageID
				Toggle struct {
					Desc MessageID
				}
			}{
				Desc:  "cmd.summon.style.desc",
				Emoji: "cmd.summon.style.emoji",
				Name:  "cmd.summon.style.name",
				Role:  "cmd.summon.style.role",
				Text:  "cmd.summon.style.text",
				Toggle: struct {
					Desc MessageID
				}{
					Desc: "cmd.summon.style.toggle.desc",
				},
			},
			Unreg: struct {
				Desc MessageID
				Set  MessageID
			}{
				Desc: "cmd.summon.unreg.desc",
				Set:  "cmd.summon.unreg.set",
			},
		},
		SummonSpecific: struct {
			Desc MessageID
		}{
			Desc: "cmd.summon_specific.desc",
		},
		Top: struct {
			Desc MessageID
		}{
			Desc: "cmd.top.desc",
		},
		UnassignNorm: struct {
			Desc       MessageID
			Example    MessageID
			NoUsers    MessageID
			Unassigned MessageID
		}{
			Desc:       "cmd.unassign_norm.desc",
			Example:    "cmd.unassign_norm.example",
			NoUsers:    "cmd.unassign_norm.no_users",
			Unassigned: "cmd.unassign_norm.unassigned",
		},
		Unreward: struct {
			Desc    MessageID
			Success MessageID
		}{
			Desc:    "cmd.unreward.desc",
			Success: "cmd.unreward.success",
		},
		User: struct {
			RemoveEmoji struct {
				Desc    MessageID
				Success MessageID
			}
			SetEmoji struct {
				Desc    MessageID
				Success MessageID
			}
			SetGender struct {
				Desc    MessageID
				Success MessageID
			}
			ShowEmoji struct {
				Desc    MessageID
				NoEmoji MessageID
				Success MessageID
			}
			ShowGender struct {
				Desc    MessageID
				Success MessageID
			}
		}{
			RemoveEmoji: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.user.remove_emoji.desc",
				Success: "cmd.user.remove_emoji.success",
			},
			SetEmoji: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.user.set_emoji.desc",
				Success: "cmd.user.set_emoji.success",
			},
			SetGender: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.user.set_gender.desc",
				Success: "cmd.user.set_gender.success",
			},
			ShowEmoji: struct {
				Desc    MessageID
				NoEmoji MessageID
				Success MessageID
			}{
				Desc:    "cmd.user.show_emoji.desc",
				NoEmoji: "cmd.user.show_emoji.no_emoji",
				Success: "cmd.user.show_emoji.success",
			},
			ShowGender: struct {
				Desc    MessageID
				Success MessageID
			}{
				Desc:    "cmd.user.show_gender.desc",
				Success: "cmd.user.show_gender.success",
			},
		},
		Weather: struct {
			Current  MessageID
			Day      MessageID
			Desc     MessageID
			Evening  MessageID
			Failed   MessageID
			Message  MessageID
			Morning  MessageID
			Night    MessageID
			Today    MessageID
			Tomorrow MessageID
		}{
			Current:  "cmd.weather.current",
			Day:      "cmd.weather.day",
			Desc:     "cmd.weather.desc",
			Evening:  "cmd.weather.evening",
			Failed:   "cmd.weather.failed",
			Message:  "cmd.weather.message",
			Morning:  "cmd.weather.morning",
			Night:    "cmd.weather.night",
			Today:    "cmd.weather.today",
			Tomorrow: "cmd.weather.tomorrow",
		},
		WhoIs: struct {
			Desc     MessageID
			Success1 MessageID
			Success2 MessageID
			Success3 MessageID
			Success4 MessageID
			Success5 MessageID
			Success6 MessageID
			Success7 MessageID
			Success8 MessageID
		}{
			Desc:     "cmd.who_is.desc",
			Success1: "cmd.who_is.success_1",
			Success2: "cmd.who_is.success_2",
			Success3: "cmd.who_is.success_3",
			Success4: "cmd.who_is.success_4",
			Success5: "cmd.who_is.success_5",
			Success6: "cmd.who_is.success_6",
			Success7: "cmd.who_is.success_7",
			Success8: "cmd.who_is.success_8",
		},
	}
	Common = struct {
		Close   MessageID
		Self    MessageID
		Weekday struct {
			Friday    MessageID
			Monday    MessageID
			Saturday  MessageID
			Sunday    MessageID
			Thursday  MessageID
			Tuesday   MessageID
			Wednesday MessageID
		}
	}{
		Close: "common.close",
		Self:  "common.self",
		Weekday: struct {
			Friday    MessageID
			Monday    MessageID
			Saturday  MessageID
			Sunday    MessageID
			Thursday  MessageID
			Tuesday   MessageID
			Wednesday MessageID
		}{
			Friday:    "common.weekday.friday",
			Monday:    "common.weekday.monday",
			Saturday:  "common.weekday.saturday",
			Sunday:    "common.weekday.sunday",
			Thursday:  "common.weekday.thursday",
			Tuesday:   "common.weekday.tuesday",
			Wednesday: "common.weekday.wednesday",
		},
	}
	Status = struct {
		Coowner     MessageID
		Disabled    MessageID
		JuniorAdmin MessageID
		Member      MessageID
		Moderator   MessageID
		Owner       MessageID
		SeniorAdmin MessageID
	}{
		Coowner:     "status.coowner",
		Disabled:    "status.disabled",
		JuniorAdmin: "status.junior_admin",
		Member:      "status.member",
		Moderator:   "status.moderator",
		Owner:       "status.owner",
		SeniorAdmin: "status.senior_admin",
	}
	System = struct {
		AddBotButton    MessageID
		BotAdded        MessageID
		BotAddedAdmin   MessageID
		BotCommands     MessageID
		Canceled        MessageID
		Gender          MessageID
		NoPermission    MessageID
		UsernameAdded   MessageID
		UsernameChanged MessageID
		UsernameDeleted MessageID
	}{
		AddBotButton:    "system.add_bot_button",
		BotAdded:        "system.bot_added",
		BotAddedAdmin:   "system.bot_added_admin",
		BotCommands:     "system.bot_commands",
		Canceled:        "system.canceled",
		Gender:          "system.gender",
		NoPermission:    "system.no_permission",
		UsernameAdded:   "system.username_added",
		UsernameChanged: "system.username_changed",
		UsernameDeleted: "system.username_deleted",
	}
	User = struct {
		Apply struct {
			Joined MessageID
		}
		Joined   MessageID
		Left     MessageID
		Returned MessageID
		Unknown  MessageID
	}{
		Apply: struct {
			Joined MessageID
		}{
			Joined: "user.apply.joined",
		},
		Joined:   "user.joined",
		Left:     "user.left",
		Returned: "user.returned",
		Unknown:  "user.unknown",
	}
)

type UserLeftData struct {
	User any
}

type UserApplyJoinedData struct {
	User any
}

type UserJoinedData struct {
	User any
}

type UserReturnedData struct {
	User any
}

type CmdChatMemberSetEmojiSuccessData struct {
	Emoji any
	User  any
}

type CmdChatMemberShowEmojiNoEmojiData struct {
	User any
}

type CmdChatMemberShowEmojiSuccessData struct {
	User  any
	Emoji any
}

type CmdChatMemberRemoveEmojiSuccessData struct {
	Emoji any
	User  any
}

type CmdChatMemberBirthdaySetSuccessData struct {
	User any
}

type CmdMarrySelfData struct {
	User any
}

type CmdMarryDirectData struct {
	Sender any
	Target any
}

type CmdMarryAnnounce6Data struct {
	Sender any
	Target any
}

type CmdMarryAutoAcceptedPolygamyData struct {
	Sender any
	Target any
}

type CmdMarryAnnounce1Data struct {
	Sender any
	Target any
}

type CmdMarryAnnounce5Data struct {
	Sender any
	Target any
}

type CmdMarryAnnouncePolygamy3Data struct {
	Sender any
	Target any
}

type CmdMarryAutoAcceptedData struct {
	Sender any
	Target any
}

type CmdMarryAnnounce3Data struct {
	Sender any
	Target any
}

type CmdMarryAnnounce4Data struct {
	Sender any
	Target any
}

type CmdMarryDirectPolygamyData struct {
	Sender any
	Target any
}

type CmdMarryBotData struct {
	Sender any
	Target any
}

type CmdMarryAnnounce2Data struct {
	Sender any
	Target any
}

type CmdMarryAnnouncePolygamy4Data struct {
	Sender any
	Target any
}

type CmdMarryRequestData struct {
	Sender any
	Target any
}

type CmdMarryAnnouncePolygamy2Data struct {
	Sender any
	Target any
}

type CmdMarryRequestPolygamyData struct {
	Sender any
	Target any
}

type CmdMarryAnnouncePolygamy1Data struct {
	Sender any
	Target any
}

type CmdMarryAnnouncePolygamy6Data struct {
	Sender any
	Target any
}

type CmdMarryBotSelfData struct {
	Sender any
}

type CmdListNormsItemData struct {
	Name  any
	Value any
}

type CmdDeleteNormDeletedData struct {
	Name any
}

type CmdDeleteNormErrNothingToDeleteData struct {
	Name any
}

type CmdPermissionShowSuccessData struct {
	Cmd    any
	Status any
}

type CmdPermissionSetSuccessData struct {
	Cmd    any
	Status any
}

type CmdRolesReserveSuccessData struct {
	Role any
}

type CmdRolesFreeSuccessData struct {
	Role any
}

type CmdAddRpSuccessData struct {
	Trigger     any
	BotUsername any
}

type CmdCrocodileStartedData struct {
	Host any
}

type CmdCrocodileCallbackWordData struct {
	Word any
}

type CmdCrocodileStartedSkippedWordsData struct {
	Host         any
	SkippedWords any
}

type CmdCrocodileContinuedData struct {
	User any
}

type CmdCrocodileWinnerData struct {
	User any
	Word any
}

type CmdCrocodileWordData struct {
	Word any
}

type CmdCrocodileTimeoutMessageData struct {
	Word any
}

type CmdWhoIsSuccess4Data struct {
	User any
	Text any
}

type CmdWhoIsSuccess5Data struct {
	User any
	Text any
}

type CmdWhoIsSuccess2Data struct {
	User any
	Text any
}

type CmdWhoIsSuccess6Data struct {
	User any
	Text any
}

type CmdWhoIsSuccess7Data struct {
	User any
	Text any
}

type CmdWhoIsSuccess8Data struct {
	User any
	Text any
}

type CmdWhoIsSuccess1Data struct {
	User any
	Text any
}

type CmdWhoIsSuccess3Data struct {
	User any
	Text any
}

type CmdModerationSetMaxWarnsSetData struct {
	Max any
}

type CmdModerationSetRoleSetData struct {
	User    any
	Changed any
}

type CmdModerationMaxWarnsShowData struct {
	Max any
}

type CmdModerationUnbanUnbannedData struct {
	User any
}

type CmdModerationSetStatusSuccessData struct {
	User   any
	Status any
}

type CmdModerationRemoveAdminSuccessData struct {
	User any
}

type CmdModerationShowWarnsEmptyData struct {
	User any
}

type CmdModerationShowWarnsItemData struct {
	Index     any
	Created   any
	Moderator any
}

type CmdModerationShowWarnsExpiresData struct {
	Until any
}

type CmdModerationShowWarnsReasonData struct {
	Reason any
}

type CmdModerationShowWarnsHeaderData struct {
	User    any
	Current any
	Max     any
}

type CmdModerationClearWarnsSuccessData struct {
	User any
}

type CmdModerationTemplatesModeratorData struct {
	Moderator any
}

type CmdModerationTemplatesWarnsData struct {
	Current any
	Max     any
}

type CmdModerationTemplatesUntilData struct {
	Until any
}

type CmdModerationTemplatesActionData struct {
	User   any
	Action any
	Until  any
}

type CmdModerationTemplatesReasonData struct {
	Reason any
}

type CmdModerationWarnListReasonData struct {
	Reason any
}

type CmdModerationWarnListHeaderData struct {
	Count    any
	MaxWarns any
}

type CmdModerationWarnListItemData struct {
	Index     any
	User      any
	Created   any
	Moderator any
}

type CmdModerationWarnListExpiresData struct {
	Until any
}

type CmdModerationUnwarnSuccessData struct {
	User  any
	Left  any
	Total any
}

type CmdManageSuccessData struct {
	Chat any
}

type CmdAddNormErrInvalidValueData struct {
	Value any
	Min   any
	Max   any
}

type CmdAddNormAddedData struct {
	Name  any
	Value any
}

type CmdAllRestsItemData struct {
	Index any
	User  any
	Until any
}

type CmdShipBotBot3Data struct {
	First  any
	Second any
}

type CmdShipNormal6Data struct {
	First  any
	Second any
}

type CmdShipNormal2Data struct {
	First  any
	Second any
}

type CmdShipNormal1Data struct {
	First  any
	Second any
}

type CmdShipBot1Data struct {
	First  any
	Second any
}

type CmdShipSelf7Data struct {
	First any
}

type CmdShipBotBot1Data struct {
	First  any
	Second any
}

type CmdShipBotBot5Data struct {
	First  any
	Second any
}

type CmdShipNormal7Data struct {
	First  any
	Second any
}

type CmdShipBot8Data struct {
	First  any
	Second any
}

type CmdShipBotBot2Data struct {
	First  any
	Second any
}

type CmdShipNormal3Data struct {
	First  any
	Second any
}

type CmdShipSelf8Data struct {
	First any
}

type CmdShipNormal8Data struct {
	First  any
	Second any
}

type CmdShipBotBot8Data struct {
	First  any
	Second any
}

type CmdShipBot2Data struct {
	First  any
	Second any
}

type CmdShipSelf1Data struct {
	First  any
	Second any
}

type CmdShipBot4Data struct {
	First  any
	Second any
}

type CmdShipNormal4Data struct {
	First  any
	Second any
}

type CmdShipSelf3Data struct {
	First any
}

type CmdShipSelf4Data struct {
	First any
}

type CmdShipNormal5Data struct {
	First  any
	Second any
}

type CmdShipSelf2Data struct {
	First any
}

type CmdShipSelf5Data struct {
	First any
}

type CmdMarriagesCategoryYearsData struct {
	Years any
}

type CmdMarriagesTogetherData struct {
	Duration any
}

type CmdRestsHistoryTotalData struct {
	Count any
}

type CmdRestsHistoryEmptyData struct {
	User any
}

type CmdRestsHistoryTitleData struct {
	User any
}

type CmdRestsHistoryItemData struct {
	Index    any
	From     any
	To       any
	Duration any
}

type CmdRestsHistoryItemReasonData struct {
	Index    any
	From     any
	To       any
	Duration any
	Reason   any
}

type CmdListRewardsTitleData struct {
	User any
}

type CmdStatsNormTitleData struct {
	Name     any
	Required any
}

type CmdStatsRestingData struct {
	RestEmoji any
}

type CmdStatsNormNotFoundData struct {
	Name any
}

type CmdStatsTotalMessagesData struct {
	TotalEmoji any
	Total      any
}

type CmdStatsNobodyToSummonData struct {
	Name any
}

type CmdStatsNewbiesData struct {
	NewbieEmoji any
}

type CmdStatsFailedData struct {
	DangerEmoji any
}

type CmdStatsUserFailedData struct {
	List     any
	User     any
	Messages any
	Required any
}

type CmdStatsTitleData struct {
	StatsEmoji any
	From       any
	To         any
}

type CmdStatsPassedData struct {
	SuccessEmoji any
}

type CmdStatsAskForSummonTextData struct {
	Norm any
}

type CmdStatsAllPassedData struct {
	SuccessEmoji any
}

type CmdStatsUserPassedData struct {
	List     any
	User     any
	Messages any
}

type CmdAdminDivorceSuccessData struct {
	User1 any
	User2 any
}

type CmdDivorceSelfData struct {
	User any
}

type CmdDivorceAnnounceData struct {
	Sender  any
	Partner any
}

type CmdDivorceAnnouncePolygamyData struct {
	Sender  any
	Partner any
}

type CmdShowNormNotFoundData struct {
	Name any
}

type CmdShowNormBodyData struct {
	Name  any
	Value any
}

type CmdProfileTotalMessagesData struct {
	TotalEmoji any
	Total      any
}

type CmdProfileNewbieExemptData struct {
	NewbieEmoji any
}

type CmdProfileActivityData struct {
	CalendarEmoji any
	Day           any
	Week          any
	Month         any
	ChartEmoji    any
	DayRolling    any
	WeekRolling   any
	MonthRolling  any
	TotalEmoji    any
	Total         any
}

type CmdProfileNormFailedData struct {
	DangerEmoji any
	Name        any
	Current     any
	Required    any
}

type CmdProfileRestUntilData struct {
	RestEmoji any
	Date      any
}

type CmdProfileRewardsData struct {
	Rewards any
}

type CmdProfileRestExemptData struct {
	RestEmoji any
}

type CmdProfileTitleData struct {
	ProfileEmoji any
	User         any
}

type CmdProfileMemberSinceData struct {
	Date any
	Days any
}

type CmdProfileMemberPeriodData struct {
	From any
	To   any
	Days any
}

type CmdProfileNormPassedData struct {
	SuccessEmoji any
	Name         any
	Required     any
}

type CmdRestRequestTextReasonData struct {
	User   any
	Date   any
	Reason any
}

type CmdRestRequestItemData struct {
	Index any
	From  any
	To    any
}

type CmdRestRequestApprovedData struct {
	User any
	Date any
}

type CmdRestRequestEmptyData struct {
	User any
}

type CmdRestRequestTextData struct {
	User any
	Date any
}

type CmdRestRequestTitleData struct {
	User any
}

type CmdMarriageActiveManyData struct {
	User  any
	Count any
}

type CmdMarriageSelfData struct {
	User any
}

type CmdMarriageActiveData struct {
	User    any
	Partner any
}

type CmdEndRestEndedData struct {
	User any
}

type CmdEndRestNotInRestData struct {
	User any
}

type CmdDelRpSuccessData struct {
	Trigger any
}

type CmdRpSpeechData struct {
	Text any
}

type CmdUserShowEmojiNoEmojiData struct {
	User any
}

type CmdUserShowEmojiSuccessData struct {
	User  any
	Emoji any
}

type CmdUserRemoveEmojiSuccessData struct {
	Emoji any
	User  any
}

type CmdUserSetGenderSuccessData struct {
	Gender any
}

type CmdUserShowGenderSuccessData struct {
	User   any
	Gender any
}

type CmdUserSetEmojiSuccessData struct {
	Emoji any
	User  any
}

type CmdUnassignNormUnassignedData struct {
	Name any
}

type CmdInactiveTitleData struct {
	InactiveEmoji any
}

type CmdInactiveUserData struct {
	List         any
	User         any
	LastActivity any
}

type CmdAdminMarrySuccessData struct {
	User1 any
	User2 any
}

type CmdAssignNormAssignedData struct {
	Name any
}

type CmdWeatherMessageData struct {
	City     any
	Current  any
	Forecast any
}

type CmdWeatherFailedData struct {
	Error any
}

type CmdWeatherCurrentData struct {
	Temp      any
	Condition any
	FeelsLike any
	Wind      any
	Humidity  any
}

type CmdChatShowWeekStartSuccessData struct {
	Weekday any
	Time    any
}

type CmdChatSetWeekStartSuccessData struct {
	Weekday any
	Time    any
}

type CmdChatShowPromptSuccessData struct {
	Prompt any
}

type CmdChatShowPrefixSuccessCustomData struct {
	Prefix any
}

type CmdChatShowNewbieThresholdSuccessData struct {
	Days any
}

type CmdChatSetPrefixSuccessCustomData struct {
	Prefix any
}

type CmdChatSetNewbieThresholdSuccessData struct {
	Days any
}

type CmdHelpEnableInfoData struct {
	Command any
	Status  any
}

type CmdHelpPageData struct {
	Page  any
	Pages any
}

type CmdHelpDisableInfoData struct {
	Command any
}

type CmdRestSetReasonData struct {
	User   any
	Date   any
	Reason any
}

type CmdRestInfoData struct {
	User any
	Date any
}

type CmdRestInfoReasonData struct {
	User   any
	Date   any
	Reason any
}

type CmdRestNoRestData struct {
	User any
}

type CmdRestSetData struct {
	User any
	Date any
}

type SystemUsernameChangedData struct {
	User        any
	OldUsername any
	NewUsername any
}

type SystemUsernameDeletedData struct {
	User        any
	OldUsername any
}

type SystemBotAddedData struct {
	Emoji any
}

type SystemBotAddedAdminData struct {
	Emoji any
}

type SystemUsernameAddedData struct {
	User        any
	NewUsername any
}

type SystemNoPermissionData struct {
	Status any
}
